### ISSUE TITLE
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

### ISSUE THREAD

**Issue by simonescalaGT** [italia/spid-php#102]
Ho installato l'ultima versione di simplesaml 1.19.1 e continua a restituirmi l'errore indicato, nel momento in cui vado a fare la validazione attraverso il Validator e clicco su "Invia Response al Service Provider"

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: State not found for id  _f259c21c1e037e06436d7a1566805c046464decfe4
Backtrace:
5 /opt/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php:118 (SAML2\Response::__construct)
4 /opt/spid-php/setup/simplesamlphp/saml2/src/SAML2/Message.php:584 (SAML2\Message::fromXML)
3 /opt/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php:98 (SAML2\HTTPPost::receive)
2 modules/saml/www/sp/saml2-acs.php:35 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by simonescalaGT** [comment]
Scusate, versione simplesaml 1.19.1

**Comment by damikael** [comment]
Ciao @simonescalaGT ,
spid-php introduce diverse patch su simpleSAMLphp, al fine di renderlo conforme alle specifiche SPID, 
per questo per aggiornare a future versioni di simpleSAMLphp occorre testare ed eventualmente riapplicare o riadattare le patch.
Al momento l'ultima versione di spid-php (3.7.0) supporta simpleSAMLphp 1.19.0.
In ogni caso l'errore da te indicato "State not found for id" si verifica quando simpleSAMLphp non riesce a recuperare correttamente la sessione salvata.
Consiglio di verificare tali situazioni come consigliato qui:
https://simplesamlphp.org/docs/stable/simplesamlphp-nostate
