### ISSUE TITLE
State not found for id

### ISSUE THREAD

**Issue by filippoma** [italia/spid-php#107]
Ho il software all'ultima versione e segnalo che spesso arriva questo messaggio dopo una login eseguita correttamente (idp poste), usando sempre la stessa utenza 1 su 10 circa ho questo messaggio

State not found for id _7998b62ad33df281887445a5aa1360be40ec0e5f25

**Comment by damikael** [comment]
L'ultima versione pubblicata su master dovrebbe risolvere il problema segnalato.
Occorre aggiornare la versione di spid-php ed eseguire:
```
composer uninstall
composer install
```
Attendo un riscontro per sapere se il problema è risolto.

Grazie

**Comment by filippoma** [comment]
Ho fatto l'aggiornamento, sembra che funzioni correttamente.

Grazie mille ed a presto
Filippo

Il giorno mer 26 mag 2021 alle ore 00:50 damikael ***@***.***>
ha scritto:
