### ISSUE TITLE
Problemi validazione metadata

### ISSUE THREAD

**Issue by francescoscialacqua** [italia/spid-php#108]
Segnalo che ci sono dei problemi nella generazione del metadata. A seguito del processo di validazione AGID mi segnala delle incongruenze che però sono gestite dal codice. Nello specifico:

- Il tasto "entra con SPID" non è conforme alle linee guida (ma quello che utilizzo è quello generato automaticamente)
- Il tag email non è corretto è presente "mailto:" (nel fiel config json è riportato solamente l'indirizzo quindi il mailto: viene aggiunto automaticamente)
- Tag private deve essere vuoto (non so quale valore venga inserito in quanto nel config non ci sono valori che popolano questo campo)

**Comment by damikael** [comment]
Buongiorno @francescoscialacqua ,
per verificare le segnalazioni, potresti indicare la URL alla quale è presente il bottone Entra con SPID generato da spid-php.

Grazie

**Comment by francescoscialacqua** [comment]
https://candidatureconcorsi.it/

**Comment by rglauco** [comment]
Mi aggiungo, ho appena ricevuto lo scarto da agid per lo stesso motivo.
Ho rifatto il processo e confermo, al passaggio
`Please insert Organization Contact Email Address (info@organization.org): ced@comune.preganziol.tv.it`
il tag risultante e' questo
`    <md:EmailAddress>mailto:ced@comune.preganziol.tv.it</md:EmailAddress>`

**Comment by francescoscialacqua** [comment]
Dai controlli fatti in tutti i file di config non è mai presente il mailto ma non trovo la classe che lo aggiunge automaticamente...

**Comment by damikael** [comment]
A breve seguirà aggiornamento che risolve il problema legato al mailto:

Riguardo al tasto Entra con SPID @francescoscialacqua i loghi e i testi dei pulsanti sono allineati al centro, mentre devono essere allineati a sinistra. Probabilmente qualche css dell'applicazione va in conflitto con lo stile del pulsante standard.

Il Tag Private, invece, contiene solo la specifica del namespace che non è in contrasto con le specifiche SPID. Consiglio di specificarlo in risposta alla segnalazione.

**Comment by damikael** [comment]
La release 3.7.1 risolve il problema relativo alla presenza di mailto: nel campo EmailAddress.
Per aggiornare la propria installazione:

1. - aggiornare la release di spid-php
2. - eseguire `composer uninstall`
3. - eseguire `composer install`

**Comment by AlessandraB19** [comment]
Scusate se riapro questo issue, ma ho avuto lo stesso riscontro ed ho effettuato l'aggiornamento dell'installazione. Al termine, ho provato ad effettuare una verifica sullo Spid Validator inserendo l'URL del nuovo metadata, ma ricevo l'errore che riporto di seguito
![errore_validator](https://user-images.githubusercontent.com/78797100/122383616-46ba5900-cf6b-11eb-9454-34625d19c18b.PNG)

**Comment by AlessandraB19** [comment]
Aggiungo che prima dell'aggiornamento, quando provavo ad accedere alla cartella myservice via web non mi richiedeva alcuna autenticazione, cosa che invece accade adesso
