### ISSUE TITLE
spid-php-sdk -> spid-php

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#11]
il repo originale si chiamava https://github.com/damikael/spid-php-sdk, questo solo spid-php

per consistenza si dovrebbe cambiare ovunque spid-php-sdk -> spid-php

```
~/spid-php$ grep -l -r spid-php-sdk | grep -v '\.git'
README.md
setup/sdk/login.tpl
setup/sdk/user.tpl
setup/Setup.php
```
e:
```
~/spid-php$ find . | grep spid-php-sdk
./setup/sdk/spid-php-sdk.tpl
```

**Comment by damikael** [comment]
Grazie @simevo ,
se vuoi, puoi provvedere tu stesso a cambiare e inviare PR.

**Comment by damikael** [comment]
Grazie @enrigen
