### ISSUE TITLE
Impossibile scaricare SP metadata

### ISSUE THREAD

**Issue by zer0uno** [italia/spid-php#111]
Sto provando a mettere mani alla libreria, l'installazione va a buon fine, modifico il file di nginx, ma quando vado a richiamare l'URL `/myservice/module.php/saml/sp/metadata.php/service` ottengo una 200 con pagina bianca. Per giunta anche la semplice chiamata ad `/myservice/` mi restituisce analogamente un 200 con pagina bianca.
La struttura delle cartelle è la seguente:
```
- root/ 
  - ...
  - spid/ (qui ho unzippato il file recuperato dal repository ed ho lanciato `composer install`)
  - ...
  - login-spid.php
  ```
Cosa potrebbe essere o quali altri informazioni posso fornire?

**Comment by zer0uno** [comment]
Ciao @damikael ho riprovato seguendo le tue indicazioni, quindi NON modificando nessuna configurazione a livello di nginx e mettedo la cartella in cui eseguire `composer install` fuori dalla root. Adesso ho la seguente situazione:

1. `http://localhost/myservice/` > 500
2. `http://localhost/myservice/index.php` > vengo ridirezionato su `http://localhost/myservice/module.php/core/frontpage_welcome.php` che a sua volta mi da un 404
3. `http://localhost/myservice/module.php/saml/sp/metadata.php/service` > 500

**Comment by damikael** [comment]
Se viene restituito error 500 provando ad accedere a /myservice o provando a scaricare il metadata l'installazione molto probabilmente non è stata completata correttamente.
Sul file di log del webserver che errori riscontri?
Quando esegui `composer install` viene eseguito tutto il processo di installazione durante il quale vengono richieste le configurazioni? Al termine della fase di installazione dovresti trovare il file spid-php-setup.json nella directory di installazione.

**Comment by zer0uno** [comment]
@damikael 

> Sul file di log del webserver che errori riscontri?
Questo l'errore `rewrite or internal redirection cycle while internally redirecting to "/myservice/module.php/saml/sp/metadata.php/service///////////`

> Quando esegui composer install viene eseguito tutto il processo di installazione durante il quale vengono richieste le configurazioni? Al termine della fase di installazione dovresti trovare il file spid-php-setup.json nella directory di installazione.

Dire che tutto va a buon fine, non vedo errori in console e il file spid-php-setup.json viene creato

**Comment by damikael** [comment]
Sembra che il problema non dipenda da spid-php ma sia causato da un loop di redirect,
occorre verificare la configurazione del web server o dell'eventuale server proxy.
Consiglio comunque di eseguire l'installazione su un server già configurato con https e dominio.
