### ISSUE TITLE
Check Validator 4 e 100 

### ISSUE THREAD

**Issue by simonescalaGT** [italia/spid-php#112]
Salve,
ho inviato tutto a AGID e sono all'ultimo ostacolo, almeno credo.
Mi scrivono che: Per i check 4 e 100 viene restituito un errore 403, diverso anche nella grafica rispetto agli altri check.
Nella pagina error.php avevo messo questo per portarmi l'errore in una pagina custom:

header("Location: /login-error-spid.php?errorMessage=".base64_encode($this->data['errorMessage']));

**Comment by damikael** [comment]
Buongiorno @simonescalaGT ,
hai verificato con una istanza locale di spid-saml-check cosa succede?

Michele

**Comment by simonescalaGT** [comment]
Salve Michele, ho installato il local validator, dove avevo fatto gli altri test.
Se vado a check response, tutto funziona perfettamente; se vado a vedere il report, mi da la numero 1 validata e tutti gli altri come "non effettuato"

**Comment by simonescalaGT** [comment]
Forse il problema è il redirect sulla mia pagina custom? meglio gestire tutto sulla pagina error.php?

**Comment by damikael** [comment]
Considera che nei casi 4 e 100, la variabile errorMessage non è presente in quanto la verifica della firma avviene prima.

**Comment by simonescalaGT** [comment]
Infatti vado a finire su questa pagina:

miourl/simplesaml/module.php/saml/sp/saml2-acs.php/service

che è una pagina bianca con messaggio di errore forbidden.
Posso intervenire con un redirect?

**Comment by damikael** [comment]
La URL /simplesaml/module.php/saml/sp/saml2-acs.php/service 
è la URL alla quale viene rediretto il flusso alla ricezione della response, in ogni caso. 
Anche nel caso di response corretta il flusso viene sempre inviato a tale URL e, in caso di errore (come anche nei casi 4 e 100) il flusso viene poi gestito sempre dalla pagina error.php.
L'errore riscontrato, 403 forbidden, lascia presupporre un problema relativo ai permessi.
Questi vengono settati nel modo corretto durante la fase di setup.
Tuttavia, verifica che la directory, link simbolico, creata con il nome del servizio indicato in fase di setup abbia permessi di accesso corretti.

**Comment by damikael** [comment]
Per verificare meglio dovresti indicarmi URL al metadata e URL alla pagina con il bottone Entra con SPID.
Se preferisci puoi inviarmi i dati in privato.

**Comment by simonescalaGT** [comment]
ti ho inviato tutto alla tua mail

**Comment by simonescalaGT** [comment]
Salve,
tutto ok ora. C'era attivato modSecurity che bloccava la pagina in questione e finiva in 403.
E' stato settato modSecurity ed ora funziona tutto.
Prima in ogni caso avevo effettuato queste operazioni:

- composer uninstall
- modificare spid-php-setup.json lasciando vuoto spDomain
- composer install
