### ISSUE TITLE
Failed to open dir: Operation not permitted

### ISSUE THREAD

**Issue by pasqualecocchiero** [italia/spid-php#113]
Salve, dopo aver lanciato il comando composer install ed aver inserito tutti i dati richiesti, a terminale è generato il seguente errore:
[Symfony\Component\Filesystem\Exception\IOException] Failed to copy "setup/simplesamlphp/simplesamlphp/templates/error.php" to "vendor/simplesamlphp/simplesamlphp/templates/error.php" because target file could not be opened for writing.
E' certamente questione di permessi della cartella templates in vendor, infatti neanche lanciando "composer uninstall" nonciò non avviene perché la medesima cartella non può essere eliminata.
E' normale avvenga ciò nonostante vendort/../../templates sia generata con l'installazione di composer?

**Comment by damikael** [comment]
Buonasera @pasqualecocchiero ,
occorre verificare come è stato installato composer e con quale utente è stata lanciata l'installazione.
Puoi provare a cancellare la directory vendor, quindi eseguire:
```
composer uninstall
composer install
```

**Comment by damikael** [comment]
Puoi prova a scaricare composer localmente e ad eseguirlo come utente corrente.
