### ISSUE TITLE
Errore redirect data

### ISSUE THREAD

**Issue by gpannullo** [italia/spid-php#114]
Salve a tutti, ho un problema forse stupido ma ci sto perdendo la testa, se a qualcuno è capitato mi può dare una mano sarebbe gradita. Il metadati è attivo, accedo alla mi pagina creata con l'esempio riportato nel file README e apparentemente tutto funziona, viene generato il bottone con la lista degli idp e sembra tutto ok... Accedo al bottone aruba, mi fa il redirect su aruba mi autentico quando faccio il submit per ritornare alla mia pagina mi da questo errore: 
`
1 www/_include.php:17 (SimpleSAML_exception_handler)

0 [builtin] (N/A)

Caused by: SimpleSAML_Error_Exception: State not found for ID spid-php_b8719ccb5b8a60ac029c1480417e259bb92f44df0d

2 /var/www/clients/client1/web11/web/spid-php/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Message.php:607 
(sspmod_saml_Message::processResponse)

1 modules/saml/www/sp/saml2-acs.php:129 (require)

0 www/module.php:135 (N/A)
`
. Penso sia un problema di configurazione saml...

Poi faccio lo stesso test non dalla pagina renderata da me ma dalla pagina spid-php/module.php/core/authenticate.php escono i vari provider, seleziono aruba, vengo rediretto sul loro sito, metto le mie credenziali e ritorno sulla pagina di test facendomi vedere tutti i dati di login. 
Ora cosa non va? Da dove dovrei iniziare a guardare? Dall'errore si capisce la causa?
Grazie Giuseppe

**Comment by damikael** [comment]
Buonasera @gpannullo ,
il problema dovrebbe essere risolto con l'ultima versione.
Aggiorna i file di spid-php all'ultima release:
https://github.com/italia/spid-php/releases/tag/v.3.7.3

Quindi esegui
```
composer uninstall
composer install
```

**Comment by gpannullo** [comment]
Non va, il problema permane, se però lo ripeto da spid-php utilizzando l'interfaccia di saml allora funziona bene....
Datemi qualche indicazione
Grazie

**Comment by gpannullo** [comment]
ho fatto l'uninstall una seconda volta ed ora mi trovo con questo errore... spid-php/setup/simplesamlphp/simplesamlphp/lib/SimpleSAML/Session.php on line 360 ho rotto tutto? che faccio?

**Comment by damikael** [comment]
Buonasera Giuseppe, 
sto analizzando il problema, intanto ti consiglio di ripristinare la versione precedente 3.7.2
https://github.com/italia/spid-php/releases/tag/v.3.7.2

**Comment by damikael** [comment]
La release 3.7.4 risolve il problema dell'errore riscontrato su Session.

**Comment by gpannullo** [comment]
Salve a tutti, confermo che aggiornando all'ultima versione il problema si è risolto, non l'ho potuto dire prima perchè nei vari tentativi di installazione/disintallazione ho rigenerato il metadata con nuovi certificati e quindi ho dovuto chiedere all'agid l'aggiornamento prima di poter testare. 
Grazie per il supporto a @damikael
