### ISSUE TITLE
IdP Test non raggiungibile

### ISSUE THREAD

**Issue by sebyspi** [italia/spid-php#116]
Buonasera,
sto provando ad eseguire dei test con l'IdP di test (https://idptest.spid.gov.it/).
Ho eseguito tutto il processo di installazione abilitando l'IdP di Test ma questo non risulta raggiungibile in quanto la connessione va in time_out.
Inoltre anche https://idp.spid.gov.it/admin/databasesprecord/new non risulta raggiungibile. 
Quindi posso affermare che l'IdP di test è down, corretto?

L'unica alternativa per effettuare test prima di mettersi in contatto con Agid è solo in locale tramite spid-saml-check?

**Comment by gio37** [comment]
Buongiorno, riscontriamo anche noi lo stesso problema. Abbiamo richiesto info tramite email a spid.tech@agid.gov.it ma ancora nessun riscontro.

**Comment by damikael** [comment]
L'IdP di test è ora nuovamente online.

**Comment by lrealdi** [comment]
Buongiorno 
l'IdP di test https://idptest.spid.gov.it/ non risulta ancora raggiungibile
![immagine](https://user-images.githubusercontent.com/14081241/122926508-3558be80-d368-11eb-9011-836f54819d4e.png)
