### ISSUE TITLE
Aggiungere ulteriore AssertionConsumerService e SingleLogoutService 

### ISSUE THREAD

**Issue by gpannullo** [italia/spid-php#119]
Salve a tutti, vorrei aggiungere al mio metadati un secondo AssertionConsumerService e SingleLogoutService, si può fare?
Grazie

**Comment by damikael** [comment]
Salve @gpannullo ,
è possibile indicare più AssertionConsumerService e SingleLogoutService nella configurazione di simpleSAMLphp:
spid-php/vendor/simplesamlphp/simplesamlphp/config/authsources.php

Puoi fare riferimento alla documentazione ufficiale:
https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-endpoints
