### ISSUE TITLE
 IdP Test non raggiungibile

### ISSUE THREAD

**Issue by lrealdi** [italia/spid-php#120]
Buongiorno 
l'IdP di test https://idptest.spid.gov.it/ non risulta ancora raggiungibile
![immagine](https://user-images.githubusercontent.com/14081241/122926508-3558be80-d368-11eb-9011-836f54819d4e.png)

_Originally posted by @lrealdi in https://github.com/italia/spid-php/issues/116#issuecomment-865950358_

**Comment by damikael** [comment]
Consiglio di segnalare il problema su spid.tech@agid.gov.it.
A breve tuttavia, sarà disponibile online il nuovo ambiente demo basato su spid-saml-check.
Nel frattempo è possibile utilizzare l'ambiente demo di spid-saml-check in locale:
https://github.com/italia/spid-saml-check#how-to-use-it-as-a-spid-demo
