### ISSUE TITLE
Problema entity id non registrato

### ISSUE THREAD

**Issue by sidelux** [italia/spid-php#121]
Buongiorno a tutti, dopo aver seguito vari passi durante l'installazione, per qualsiasi opzioni io tenti durante il login mi appare un errore simile a `L'entity ID "***" indicato nell'elemento <Issuer> non corrisponde a nessun Service Provider registrato in questo Identity Provider di test.` o `Formato richiesta non corretto.` e non saprei come capire dove sta il problema.

Onestamente ho fatto molta fatica a seguire la documentazione, ci sono altre guide più dettagliate?

**Comment by damikael** [comment]
Buongiorno @sidelux ,
il metadata del Service Provider implementato con spid-php deve essere registrato presso l'Identity Provider affinché le AuthnRequest possano essere riconosciute valide, ovvero provenienti da un soggetto SP appartenente alla federazione.

Ti consiglio di approfondire il funzionamento del meccanismo di autenticazione del protocollo SAML secondo il profilo Web SSO.

Per registrare, ad esempio, il metadata del SP implementato con spid-php presso l'IdP demo https://demo.spid.gov.it occorre registrare il metadata che viene generato all'indirizzo _/myservice/module.php/saml/sp/metadata.php/service_ (dove myservice è il nome del servizio come specificato durante l'installazione) tramite l'interfaccia disponibile su https://demo.spid.gov.it/validator

**Comment by nicolastorgato** [comment]
Buongiorno,
io ho seguito tutti i passi indicati nell'ambiente demo (https://demo.spid.gov.it/), ma quando tento di inviare una AuthnRequest al IdP di test, mi viene tornato questo errore: 
```
Formato richiesta non corretto. La AuthnRequest non supera i controlli strict.
Verificare la AuthnRequest tramite uno strumento di validazione.
```

Preciso che nello Spid Validator tutti i controlli vengono superati correttamente. Come posso fare?
