### ISSUE TITLE
Setup configuration openssl Error

### ISSUE THREAD

**Issue by alessandrobozo** [italia/spid-php#122]
Ciao,

in fase di configurazione ho ricevuto questo errore, è la prima volta che mi si presenta. Sapete dirmi il perchè?
![Immagine 2021-07-07 180658](https://user-images.githubusercontent.com/59022784/124793324-28ce8b80-df4e-11eb-8549-867099a8627a.png)
Grazie.

**Comment by damikael** [comment]
Ciao @alessandrobozo , prova ad aggiornare openssl.
Vedi #67
