### ISSUE TITLE
Formato richiesta non corretto. Verificare che il metadata sia stato registrato.

### ISSUE THREAD

**Issue by cod3rshotout** [italia/spid-php#125]
Ciao @damikael 

sono riuscito ad eseguire lo script correttamente, recandomi su public_html/login-spid.php riesco a visualizzare il pulsante dello spid.

Sto però avendo il seguente errore: 

<img src="https://i.imgur.com/UIc6w8k.jpg">

Ho visto che un altro utente ha segnalato la cosa qui: https://github.com/italia/spid-php/issues/46

e pur seguendo le tue indicazioni, e cioè di visionare a cosa corrisponde il messaggio di errore leggendo da qui (punto 10):
https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/spid_tabella_messaggi_di_anomalia_v1.0.pdf

non riesco a capire come sistemare il problema. C'è qualche configurazione che ho omesso in simplesaml?

Grazie

PS: l'errore lo da anche su demo

**Comment by damikael** [comment]
Ciao @cod3rshotout ,

affinchè il protocollo di autenticazione SAML / SPID funzioni, il metadata dell'IdP deve essere registrato presso il SP e, viceversa, il metadata del SP deve essere registrato presso l'IdP. 
spid-php provvede in maniera automatica a registrare direttamente i metadata degli IdP SPID e dell'IdP Demo; manca invece il passaggio di registrazione del SP, allestito con spid-php, sugli IdP.
La registrazione agli IdP SPID reali avviene, a seguito di notifica da parte di AgID agli IdP, dopo aver superato il collaudo ufficiale.
Per la registrazione sull'IdP Demo, invece, occorre registrare in autonomia il metadata del proprio SP alla seguente URL:
https://demo.spid.gov.it/validator

Il metadata di un SP allestito con spid-php può essere scaricato da:
/_myservice_/module.php/saml/sp/metadata.php/service
dove _myservice_ è il nome del servizio come specificato durante l'installazione.

Michele

**Comment by cod3rshotout** [comment]
@damikael grazie per la risposta, il problema è che anche cliccando su demo ottengo lo stesso errore. Sono andato su https://demo.spid.gov.it/validator e ho inserito l'url per il download del metadata, ho ottenuto la risposta del file xml ma poi non so come procedere, potresti indicarmi nel dettaglio tutti i passaggi?

**Comment by cod3rshotout** [comment]
Ciao @damikael  grazie per la risposta, nella validazione ottengo il seguente messaggio di errore: 

The Location attribute must be a valid HTTPS url - TR pag. 20 and AV n° 1

**Comment by damikael** [comment]
Sì, il servizio di autenticazione deve essere esposto su HTTPS.

**Comment by cod3rshotout** [comment]
Ciao @damikael 

attualmente ho: The Location attribute in SingleLogoutService element must be a valid URL - AV n° 1 and n° 3

guardando nel file xml però è già su https:

    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://localhost/myservice/module.php/saml/sp/saml2-logout.php/service"/>

come risolvo?

**Comment by cod3rshotout** [comment]
Ciao @damikael  sono riuscito a correggere l'errore cambiando in `https://www.localhost`

tutti i test di convalida sono stati superati, e mi riferisco a xsd, strict, certificates ed extra. Quando avvio la modalità demo però ottengo il seguente errore:

<img src="https://i.imgur.com/yrkOEDq.jpg">

questi sono i controlli strict:

<img src="https://i.imgur.com/oNfM833.png">

**Comment by damikael** [comment]
ok per il metadata, devono essere superati anche tutti i test della sezione Request, per poter poi accedere a Demo

**Comment by cod3rshotout** [comment]
@damikael ci siamo quasi, incrociando le dita. L'errore del response è il seguente:

<img src ="https://i.imgur.com/aeNsWTn.jpg">

ma nell'xml ho:

    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://www.localhost/myservice/module.php/saml/sp/saml2-acs.php/service" index="0" isDefault="true"/>

**Comment by damikael** [comment]
puoi riportare uno screenshot della Request SAML (sezione Request -> SAML inviando richiesta di autenticazione a SPID Demo (Validator Mode)

**Comment by cod3rshotout** [comment]
@damikael 

<img src="https://i.imgur.com/lRmY1eR.jpg">

**Comment by cod3rshotout** [comment]
Ciao @damikael 
sono riuscito a configurare lo spid e finalmente non ottengo più errori. L'ho configurato su un ambiente docker con proxy + letsencrypt per la gestione automatica dell'ssl e sembra che funzioni tutto correttamente.

Ho soltanto una domanda: dopo aver effettuato l'accesso con uno degli utenti di test, la demo mi reindirizza ad una pagina di errore:

    https://example.com/myservice/errorreport.php

contenente il seguente debug:

    Backtrace:
    1 www/_include.php:17 (SimpleSAML_exception_handler)
    0 [builtin] (N/A)
    Caused by: PHPMailer\PHPMailer\Exception: Invalid address:  (From): 
    Backtrace:
    2 /var/www/html/spid-php/vendor/phpmailer/phpmailer/src/PHPMailer.php:1284 (PHPMailer\PHPMailer\PHPMailer::setFrom)
    1 lib/SimpleSAML/Utils/EMail.php:48 (SimpleSAML\Utils\EMail::__construct)
    0 www/errorreport.php:52 (N/A)

ti chiedo: perché si verifica quest'errore dopo l'autenticazione?

**Comment by cod3rshotout** [comment]
ciao @damikael 

ho installato simplesaml su un altro server di produzione, ma sto avendo problemi con "too many redirect". Questa è la configurazione di nginx:

    location /myservice/ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO       $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED $document_root$fastcgi_path_info;

        fastcgi_pass   php-upstream;
        fastcgi_index  index.php;
    }

come posso risolvere?

**Comment by damikael** [comment]
Verifica innanzitutto di avere l'ultima versione di spid-php.
L'errore **ErrorCode nr20** come indicato in:
https://www.agid.gov.it/sites/default/files/repository_files/tabella-messaggi-spid-v1.3_0.pdf
dipende da "Utente privo di credenziali compatibili con il livello richiesto dal fornitore del servizio".
Molto probabilmente è stata eseguita una autenticazione con un utente avente credenziali con livello SPID minore di quello richiesto dal SP.
Riguardo alla configurazione di nginx prova ad utilizzare la configurazione riportata nell'esempio sul README.

**Comment by cod3rshotout** [comment]
Ciao @damikael 
ti ho appena girato un email, potresti dargli un'occhiata?

Grazie
