### ISSUE TITLE
Formato non valido

### ISSUE THREAD

**Issue by alexmari81** [italia/spid-php#126]
Buongiorno,
Ho eseguito la procedura e sto utilizzando lo spid validator, ho sostituito qui il nome del dominio con 'miodominio'.

Il checkXsd mi segnala quanto segue:

`the metadata must validate against the XSD stderr: ./data/http___miodominio_it/sp-metadata.xml:40: element Company: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}Company': This element is not expected. Expected is ( {urn:oasis:names:tc:SAML:2.0:metadata}Extensions ). stderr: ./data/http___miodominio_it/sp-metadata.xml fails to validate`

Il CheckStrict mi segnala 2 errori:

- `7 | Only one default AssertionConsumerService must be present - TR pag. 20 | failure`
- 
- `8 | Must be present the default AssertionConsumerService with index = 0 - TR pag. 20`

In effetti nel metadata ho:

```
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://www.miodominio.it/myservice/module.php/saml/sp/saml2-acs.php/service" index="0"/>
        
    
        <md:AttributeConsumingService index="1">
            
      
            <md:ServiceName xml:lang="it">
                Service Provider Name
            </md:ServiceName>
            
      
            <md:ServiceDescription xml:lang="it">
                Service Provider Description
            </md:ServiceDescription>
            
      
            <md:RequestedAttribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
            
      
            <md:RequestedAttribute Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
            
      
            <md:RequestedAttribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
            
      
            <md:RequestedAttribute Name="placeOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
            
    
        </md:AttributeConsumingService>
```

Come posso risolvere?

Va considerato che sto inserendo il bottone all'interno del CMS Drupal, non ho incluso le classi con _autoload.php ma in un altro modo altrimenti Drupal va in pagina bianca, non so se possa influire, fin ora però il pulsante funziona ma non il metadato.

**Comment by damikael** [comment]
Buongiorno @alexmari81 ,
l'installazione del SP deve essere eseguita necessariamente da linea di comando tramite l'istruzione:
composer install
in quanto lo script durante la fase di installazione applica patch al codice standard di simpleSAMLphp ed esegue modifiche alle configurazioni.
Verifica quindi di seguire il processo di installazione come indicato sul README.
Per l'integrazione in Drupal, puoi utilizzare l'installazione spid-php come proxy.
