### ISSUE TITLE
Errore "eccezione non gestita" durante download metadata

### ISSUE THREAD

**Issue by mazzalin1orangepix** [italia/spid-php#127]
Per un sito in nostra gestione stiamo cercando da diverso tempo di implementare la soluzione login con spid.

attualmente abbiamo installato questa libreria per generare il metadata.
Abbiamo eseguito l'installazione su un server plesk a fine di testarla visto che in locale non riuscivamo ad eseguirla.

Otteniamo sia in locale che su server di prova questo errore in foto quando cerchiamo di scaricare il file metadata di prova.
Unable to load certificate/public key from file "/var/www/vhosts/orangepix.it/subdomains/temp/httpdocs/spid-php/vendor/simplesamlphp/simplesamlphp/cert/spid-sp.crt

![Schermata 2021-07-20 alle 14 32 15](https://user-images.githubusercontent.com/79647819/126324597-6cdcd85d-9f2c-4655-b5cf-68cc8ba0c1a3.jpg)

troviamo infatti generato il file .pem ma non viene generato quello .crt
A cosa può essere dovuta questa eccezione?

**Comment by damikael** [comment]
Buongiorno @mazzalin1orangepix ,
verifica se riscontri errori durante la fase di installazione ed in particolare durante la creazione del certificato.
Potrebbe dipendere dalla versione di openssl installata sul sistema.
Vedi anche: #122 , #67
