### ISSUE TITLE
Stato non trovato

### ISSUE THREAD

**Issue by MLorenzoni** [italia/spid-php#132]
Salve,

sto integrando la libreria spid-php con un applicativo sviluppato tramite JOOMLA. Quando provo ad effettuare il test della response tramite SPID Validator ricevo il seguente messaggio di errore.

> Backtrace:
> 1 www/_include.php:17 (SimpleSAML_exception_handler)
> 0 [builtin] (N/A)
> Caused by: Exception: State not found for id  _96e6a4949196954ac0b9d881bb196cdb11edfd1557
> Backtrace:
> 5 /var/www/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php:118 (SAML2\Response::__construct)
> 4 /var/www/spid-php/setup/simplesamlphp/saml2/src/SAML2/Message.php:584 (SAML2\Message::fromXML)
> 3 /var/www/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php:98 (SAML2\HTTPPost::receive)
> 2 modules/saml/www/sp/saml2-acs.php:35 (require)
> 1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
> 0 www/module.php:10 (N/A)

E' un problema causato dall'integrazione con JOOMLA oppure e' legato alla libreria?

Grazie

**Comment by damikael** [comment]
Il problema è legato alla perdita di sessione su SimpleSAMLphp. Può verificarsi, ad esempio, nel caso in cui il SP è collegato con un dominio (es. example.com) e l'applicativo avvia il processo di autenticazione da un dominio diverso (es. www.example.com).

In ogni caso, consiglio di verificare le possibili cause in relazione a quanto indicato per SimpleSAMLphp:
https://simplesamlphp.org/docs/stable/simplesamlphp-nostate

**Comment by MLorenzoni** [comment]
> 
> 
> Il problema è legato alla perdita di sessione su SimpleSAMLphp. Può verificarsi, ad esempio, nel caso in cui il SP è collegato con un dominio (es. example.com) e l'applicativo avvia il processo di autenticazione da un dominio diverso (es. [www.example.com](http://www.example.com)).
> 
> In ogni caso, consiglio di verificare le possibili cause in relazione a quanto indicato per SimpleSAMLphp:
> https://simplesamlphp.org/docs/stable/simplesamlphp-nostate

@damikael 
Buonasera, ho controllato il dominio ed e' lo stesso. Ho dato anche un occhio al link della documentazione ma mi sembra tutto ok. Come ultima prova ho provato a spostare il login su un sito completamente esterno a joomla e il tutto ha funzionato correttamente, quindi probabilmente il problema e' proprio joomla che in qualche modo modifica/elimina i dati nella sessione che servono a SPID. Se hai mai usato joomla, hai qualche idea su come poter sistemare?

**Comment by herald-si** [comment]
Non so per joomla, ma per drupal è necessario impostare il session storage del config di simplesamlphp a qualcosa di diverso da "phpsession", proprio per come l'applicativo gestisce le sessioni.
https://www.drupal.org/project/simplesamlphp_auth
> Prerequisites
>SimpleSAMLphp - you must have SimpleSAMLphp version 1.6 or newer installed and configured to operate as a service provider (SP).
>NOTE: Your SimpleSAMLphp SP must be configured to use something other than "phpsession" (the default) for session storage. The alternatives are memcache or sql. The sql option was added in SimpleSAMLphp version 1.7. The simplest solution for folks running SimpleSAMLphp version 1.7 or higher is to edit the SimpleSAMLphp config/config.php by setting store.type => 'sql' and 'store.sql.dsn' => 'sqlite:/path/to/sqlitedatabase.sq3'

**Comment by MLorenzoni** [comment]
> 
> 
> Non so per joomla, ma per drupal è necessario impostare il session storage del config di simplesamlphp a qualcosa di diverso da "phpsession", proprio per come l'applicativo gestisce le sessioni.
> https://www.drupal.org/project/simplesamlphp_auth
> 
> > Prerequisites
> > SimpleSAMLphp - you must have SimpleSAMLphp version 1.6 or newer installed and configured to operate as a service provider (SP).
> > NOTE: Your SimpleSAMLphp SP must be configured to use something other than "phpsession" (the default) for session storage. The alternatives are memcache or sql. The sql option was added in SimpleSAMLphp version 1.7. The simplest solution for folks running SimpleSAMLphp version 1.7 or higher is to edit the SimpleSAMLphp config/config.php by setting store.type => 'sql' and 'store.sql.dsn' => 'sqlite:/path/to/sqlitedatabase.sq3'

Ho provato a fare come hai detto tu e funziona. Grazie mille
