### ISSUE TITLE
Problemi con il Logout

### ISSUE THREAD

**Issue by andreakappa** [italia/spid-php#136]
Seguendo la documentazione, 
per impostare il redirect dopo il logout, passiamo l'url alla funzione di logout, 
tuttavia (anche se con il debugger vediamo che al logout arriva correttamente il parametro) 
la pagina torna sempre sulla pagina di logout di simplesamlphp

 con scritto: 

```
Disconnesso
Sei stato disconnesso

[ Torna alla pagine di installazione di SimpleSAMLphp ]
```

In aggiunta dopo il logout, la sessione non viene distrutta rendendo poi impossibile un nuovo login con il solito problema dello state di simplesaml.

**Comment by damikael** [comment]
Potrebbe essere un problema di errata configurazione o installazione perchè non riscontro l'anomalia. 
La funzione è implementata come segue, ad esempio ?

```
<?php 
    require_once("/path/to/spid-php.php");
    $spidsdk = new SPID_PHP();

    $spidsdk->logout("/login-spid.php");
?>
```

Verificare anche se il problema si presenta con la funzione getLogoutURL

**Comment by andreakappa** [comment]
Se faccio il logout senza fare prima il login funziona. Ho notato, debuggando l'Auth Simple, che quando é presente un auth source (e quindi si é loggati realmente)  la riga evidenziata sotto non ritorna ma esce subito, mandandomi al redirect che indicavo di SimpleSAMLphp.
Quindi l'handler, contenente i parametri di redirect, non viene proprio invocato.


    public function logout($params = null)
    {
        assert(is_array($params) || is_string($params) || $params === null);
        if ($params === null) {
            $params = Utils\HTTP::getSelfURL();
        }

        if (is_string($params)) {
            $params = [
                'ReturnTo' => $params,
            ];
        }

        assert(is_array($params));
        assert(isset($params['ReturnTo']) || isset($params['ReturnCallback']));

        if (isset($params['ReturnStateParam']) || isset($params['ReturnStateStage'])) {
            assert(isset($params['ReturnStateParam'], $params['ReturnStateStage']));
        }

        if ($this->session->isValid($this->authSource)) {
            $state = $this->session->getAuthData($this->authSource, 'LogoutState');
            if ($state !== null) {
                $params = array_merge($state, $params);
            }
            **$this->session->doLogout($this->authSource);**
            $params['LogoutCompletedHandler'] = [get_class(), 'logoutCompleted'];

            $as = Source::getById($this->authSource);

            if ($as !== null) {
                $as->logout($params);
            }
        }
        self::logoutCompleted($params);
    }

**Comment by damikael** [comment]
Il logout si esegue con la funzione logout dell'sdk spid-php?

```
        public function logout($returnTo = null, $saml_logout = true) {
            if($saml_logout) {
                $this->spid_auth->logout($returnTo);
            } else {
                $session = SimpleSAML_Session::getSessionFromRequest();
                if ($session->isValid('service')) {
                    $session->doLogout('service');
                }
            }
        }
```

Per caso è stato modificato il nome dell'authsource predefinito (service) ?

**Comment by andreakappa** [comment]
Si, la funzione é identica a quella
anche il nome dell'authsource, guardando dentro ai file vedo che é sempre 'service' 

Unica cosa, nel file spid-php-setup.json trovo questo parametro

`sloCustomLocation` impostato all'url che ho indicato prima, sembra che faccia sempre un fallback su questo.

**Comment by damikael** [comment]
sloCustomLocation serve a modificare la location di SingleLogout all'interno del metadata.
Può tuttavia essere modificato esclusivamente se sul web server può essere attivato opportuno redirect da sloCustomLocation alla URL di SimpleSAMLphp che gestisce il logout.

Imposta:
```
acsCustomLocation: ""
sloCustomLocation: ""
```

Registra nuovamente il metadata del SP sull'IdP 
e verifica se ora il logout funziona.

**Comment by andreakappa** [comment]
Grazie, svuotando quei campi sembra funzionare correttamente. 
Anche l'altro problema (relativo al secondo login dopo il logout) si é risolto.
