### ISSUE TITLE
Orario dei log in formato UTC

### ISSUE THREAD

**Issue by trinko** [italia/spid-php#138]
Ho visto che, seppure nei documenti tecnici non ho trovato nulla, nella convenzione per le PA è richiesto a proposito dei log che il SP deve *"garantire che agli eventi registrati (log) sia apposto un riferimento temporale che corrisponda alla scala di tempo UTC (IEN)"*.

Vedo che i log di simplesamlphp riportano invece l'orario in formato italiano.

**Comment by damikael** [comment]
Risolto qui: https://github.com/italia/spid-php/commit/69596e114824dba2a4e7f6ed037b616033f4204f
