### ISSUE TITLE
Metadata con più AssertionConsumerService e SingleLogoutService, dove settare AttributeConsumingServiceIndex

### ISSUE THREAD

**Issue by alessandrobozo** [italia/spid-php#144]
In relazione alla [issue #80](https://github.com/italia/spid-php/issues/80) mi sapreste dire in fase di request e di logout dal validator dove devo andare ad impostare l'index del AttributeConsumingServiceIndex?
Grazie Alessandro

**Comment by damikael** [comment]
Buonasera @alessandrobozo ,
come indicato nel README, la chiamata al metodo login può essere effettuata indicando come terzo parametro l'indice dell'AttributeConsumingService richiesto. Ad esempio, la chiamata di login verso IdP Validator per livello SPID 1 e AttributeConsumingServiceIndex 1, è la seguente

```
$spidsdk = new SPID_PHP();
$spidsdk->login('VALIDATOR', 1, null, 1);  
```              

Saluti,
Michele

**Comment by alessandrobozo** [comment]
Grazie mille Michele.
