### ISSUE TITLE
Errore durante la creazione del certificato spid-sp.crt

### ISSUE THREAD

**Issue by salvorapi** [italia/spid-php#147]
Salve,

durante la fase di setup si presenta un problema nel caso in cui i parametri scritti nel file spid-php-openssl.cnf nella sezione dn sono vuoti.

I parametri richiesti in fase di setup sono:

- spOrganizationName
- spOrganizationDisplayName
- spOrganizationIdentifier
- spCountryName
- spLocalityName

Bisognerebbe mettere un valore di default o rendere obbligatorio l'ingresso dei parametri.

**Comment by heliosciancio** [comment]
Trattandosi dei parametri di generazione del certificato, credo sia più appropriato rendere obbligatori i campi piuttosto che impostare valori di default.

**Comment by salvorapi** [comment]
> Trattandosi dei parametri di generazione del certificato, credo sia più appropriato rendere obbligatori i campi piuttosto che impostare valori di default.

L'obbligo dei campi è sicuramente una buona idea. Tuttavia, in fase di test, potrebbe essere utile avere dei valori di default per poter effettuare delle prove. Che ne pensi @heliosciancio  ?

**Comment by heliosciancio** [comment]
Vada per il valore di default. Scelta in linea con quanto fatto per gli altri parametri.

Cosa usiamo: `Località da specificare`, `Roma` o altro?

**Comment by damikael** [comment]
Alcuni valori di default sono già presenti:
https://github.com/italia/spid-php/blob/303b5e01367d4db922dc731aeb4169e04a071df9/setup/Setup.php#L44

Dovrebbe mancare solo il codice ente:
https://github.com/italia/spid-php/blob/303b5e01367d4db922dc731aeb4169e04a071df9/setup/Setup.php#L57
utilizziamo "_code_" 
anche se non dovrebbe essere un problema perchè spOrganizationIdentifier viene poi costruito insieme con spOrganizationCodeType quindi non dovrebbe essere mai vuoto

e la località:
https://github.com/italia/spid-php/blob/303b5e01367d4db922dc731aeb4169e04a071df9/setup/Setup.php#L55
utilizziamo "_locality_".
