### ISSUE TITLE
Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio

### ISSUE THREAD

**Issue by amottaConsorzioInnovo** [italia/spid-php#148]
Sto utilizzando il progetto per integrarlo su un'applicazione esistente ho creato un'applicazione web ad-hoc cheenb accoglie il progetto spid-php e personalizzato la pagina di login.

Utilizzato in test non ha riscontrato problemi, quando siamo passati ad utilizzarlo con i veri IDP stiamo riscontrando il problema.

Il metadata del nostro SP è condiviso con un'altra applicazione web ed è l'altra applicazione che pubblica il metadato

Impostando la modalità debug riscontriamo nel log che manca nel saml:Authnrequest il tag ds:signature c'è qualche errore nel setup o è un limite del progetto.

**Comment by damikael** [comment]
Se non vengono riscontrati problemi con demo.spid.gov.it non dovrebbero esserci in generale problemi con gli IdP reali.
Per verificare meglio il problema occorre avere riferimenti alla URL del metadata e alla pagina dove è presente il bottone "Entra con SPID"
