### ISSUE TITLE
Nginx - Missing snakeoil certificate - Certificato snakeoil mancante

### ISSUE THREAD

**Issue by paulocoghi** [italia/spid-php#155]
When using Nginx, the snippets/snakeoil.conf configuration file expects that /etc/ssl/certs/ssl-cert-snakeoil.pem already exists, otherwise Nginx will not work.

I created the PR #154 which add instructions about it on README.

--

Quando si utilizza Nginx, il file di configurazione snippets/snakeoil.conf prevede che /etc/ssl/certs/ssl-cert-snakeoil.pem esista già, altrimenti Nginx non funzionerà.

Ho creato il PR #154 che aggiunge istruzioni a riguardo su README.

**Comment by damikael** [comment]
Fixed with #154
