### ISSUE TITLE
Error use of undefined constant nel log

### ISSUE THREAD

**Issue by nicofari** [italia/spid-php#157]
Nel log appare un errore

 SimpleSAML\Error\Exception: Error 2 - Use of undefined constant familyName - assumed 'familyName' (this will throw an Error in a future version of PHP) at /code/vendor/simplesamlphp/simplesamlphp/config/authsources.php:59

per ogni attributo spid che è stato richiesto e messo nella configurazione di SimpleSamlPhp.
Qui ho riportato solo quello per familyName

Php 7.4.20-fpm

**Comment by nicofari** [comment]
ho capito la causa del problema. Mi sono sbagliato scusate.
Il frammento che vedete sopra è preso da un altro progetto, in quello dove ho il problema effettivamente la riga è così:
'attributes' => array(spidCode,name,familyName,placeOfBirth,countyOfBirth,dateOfBirth,gender,companyName,registeredOffice,fiscalNumber,ivaCode,idCard,expirationDate,mobilePhone,email,address,digitalAddress,domicileStreetAddress,domicilePostalCode,domicileMunicipality,domicileProvince,domicileNat
ion),

quindi mancano effettivamente gli apici.
Non è colpa di spid-php, ho fatto un "adattamento" per utilizzare il formato yaml e nel farlo ho rotto questa parte.
Chiudo la issue, grazie e scusate per il tempo perso.

**Comment by damikael** [comment]
Nessun problema @nicofari , ogni esperienza è utile a tutti.
