### ISSUE TITLE
Mancato controllo sulla presenza di una versione corretta di OpenSSL 

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-php#160]
Sebbene OpenSSL sia un prerequisito alla libreria, non viene eseguito un controllo sulla sue presenza e sull'eventuale versione installata.
In caso di mancata presenza di OpenSSL, la procedura di installazione procede  ma non vengono generati i certificati.

Procedura suggerita per la risoluzione della issue:

1. Verifica della presenza di una versione corretta di OpenSSL
2. A seconda che si ritenga il prerequisito vincolante o meno, si dovrebbe rispettivamente:

- Terminare d'ufficio la procedura d'installazione
- Lanciare un warning sulla mancata presenza di OpenSSL, lasciando facoltà all'utente se proseguire o terminare la procedura d'installazione.

**Comment by damikael** [comment]
Il requisito può essere gestito tramite composer
