### ISSUE TITLE
configurazione certificati di produzione

### ISSUE THREAD

**Issue by andreakappa** [italia/spid-php#162]
una volta ottenuto il certificato firmato, dove é possibile configurarne il path?
ho trovato i riferimenti a quello self-signed solo nei template di setup: 

- setup/config/authsources_private.tpl 
- setup/config/authsources_public.tpl 

posso modificare quei file, oppure devo sovrascrivere il certificato  self-signed? 
peró in quel caso per averlo anche nel metadata é automatica la cosa?

Grazie

**Comment by damikael** [comment]
Buongiorno,
i path sono configurabili in:
_spid-php/vendor/simplesamlphp/simplesamlphp/config_
In particolare in _config.php_ è possibile configurare la directory
mentre in _authsources.php_ è possibile configurare i nomi dei file
Suggerisco, in ogni caso di effettuare backup dei self-signed e salvare entrambi i nuovi certificati con gli stessi nomi dei self-signed nelle seguenti directory:

1. spid-php/vendor/simplesamlphp/simplesamlphp/cert
2. spid-php/cert

in quanto:

1. è la directory effettiva (relativa alla configurazione predefinita) dalla quale i certificati vengono letti.
2. è la directory utilizzata dallo script spid-php per ripristinare l'ambiente  in caso di reinstallazione.

Il metadata alla url
_/myservice/module.php/saml/sp/metadata.php/service_
viene generato sempre automaticamente dai certificati in 1.

**Comment by andreakappa** [comment]
Ok grazie, con la sovrascrittura ho visto che ha funzionato.
