### ISSUE TITLE
Problemi logout con InfoCert

### ISSUE THREAD

**Issue by voidloop** [italia/spid-php#167]
Ciao @damikael, 

stiamo riscontrando problemi con InfoCert durante il logout. Il problema sembra che la "Destination" della LogoutResponse che arriva da InfoCert sia la AssertionConsumerService, con binding HTTP_POST, invece che il SingleLogoutService specificato nei nostri metadati (con HTTP_REDIRECT). 

Pensi che sia un problema dei nostri metadati che non accettano HTTP_POST sul SingleLogoutService? o di InfoCert per qualche motivo? 

L'errore è questo:

```
SimpleSAML\Error\BadRequest: BADREQUEST('%REASON%' => 'Invalid message received to AssertionConsumerService endpoint.')
Backtrace:
2 /opt/spid-php/vendor/simplesamlphp/simplesamlphp/modules/saml/www/sp/saml2-acs.php:37 (require)
1 /opt/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 /opt/spid-php/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)
```

Grazie,
Marco

**Comment by damikael** [comment]
Ciao @voidloop ,
se il problema si verifica solo con InfoCert, credo sia piuttosto un problema dell'IdP.
Per analizzare meglio potresti inviarmi in privato dump della LogoutResponse e Metadata SP.

Michele

**Comment by nicola-milani** [comment]
@voidloop il problema è rientrato o è ancora presente?

**Comment by voidloop** [comment]
Ciao @damikael, proprio questa mattina mi ha contattato InfoCert. Il problema era sull'IdP, hanno sistemato.
Grazie ancora.
