### ISSUE TITLE
Spid-php doesn't load on the local ubuntu machine

### ISSUE THREAD

**Issue by dininni8319** [italia/spid-php#168]
Ciao a tutti.  Sto avendo dei problemi con ubuntu ed nginx. Per adesso vorrei solo visualizzare la libreria di SPID-PHP in locale. Ho clonato il progetto. Configurato nginx, installato composer e tutte le librerie richieste nella documentazione. Ho seguito la documentazione del READ.me.
Nginx funziona. Mi posso collegare con nginx in locale. Mi posso collegare anche con un file php. Ma quando provo con login-spid.php non funziona.
Allego qui la mia configurazione di nginx. 

server {  
  server_name 172.16.6.126;
  root /var/www/html/spid-php/public;
  include snippets/snakeoil.conf;  
  
  location / {
    try_files $uri $uri/ =404;
    index logi-php.php index.php;
    location ~ \.php$ {
      include snippets/fastcgi-php.conf;  
      fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;  
    }
  }
  
  location /myservice/ {
    index index.php;
    location ~ \.php(/|$) {
      fastcgi_split_path_info ^(.+?\.php)(/.+)$;
      try_files $fastcgi_script_name =404;
      set $path_info $fastcgi_path_info;
      fastcgi_param PATH_INFO $path_info;
      fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;  
      fastcgi_index index.php;
      include fastcgi.conf;
    }
  }
}

**Comment by cristianpibia** [comment]
Potresti inserire il tuo error log? a intuizione potrebbe essere l'fpm sock che è 7.0 e non 7.4

**Comment by damikael** [comment]
Concordo con @cristianpibia , consiglio inoltre di verificare che il nome del servizio "_serviceName_" configurato in fase di installazione e riportato nel file spid-php-setup.json sia uguale alla location configurata in nginx, ovvero "_myservice_"

**Comment by dininni8319** [comment]
Ciao @cristianpibia. Scusa per la mia risposta in ritardo. No riscontro nessun errore e solo che non riesco a collegarmi la SPID. Farò come ha detto @damikael di controllare il service name e la configurazione di nginx del "myservice". Per quanto riguarda la sock ho installato la versione 7.4 di php cli. Ho anche controllato le configurazioni di fpm e sembra tutto ok, quelle fornite su github penso che siano valide per la versione 7.4. Domani a lavoro controllerò questi punti da voi suggeriti e vi farò sapere. Negli ultimi due giorni ho dovuto lasciare questo progetto in stand by.  Vi ringrazio per i vostri suggerimenti e la vostra disponibilità nel aiutare gli altri. Spero un giorno di poter ricambiare il favore. Buona serata.
