### ISSUE TITLE
Setting secure cookie on plain HTTP is not allowed

### ISSUE THREAD

**Issue by fredericks** [italia/spid-php#169]
Ciao,

sto cercando di usare questo progetto.
Ho eseguito lo script composer (anche se ho dovuto eseguire **composer update** per eseguire la parte interattiva).

Seguendo le istruzioni dovrei scaricare il metadata del service provider all'indirizzo:

/myservice/module.php/saml/sp/metadata.php/service

Tuttavia mi dà questo errore, sia se provo dall'indirizzo local (quindi sotto http) sia usando l'endpoint https generato da ngrok:

Uncaught SimpleSAML\Error\CriticalConfigurationError: The configuration is invalid: Setting secure cookie on plain HTTP is not allowed. in C:\Sviluppo\spid\server\spid-php-master\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\Session.php:307
Stack trace:
#0 C:\Sviluppo\spid\server\spid-php-master\setup\simplesamlphp\simplesamlphp\lib\SimpleSAML\Error\Error.php(190): SimpleSAML\Session::getSessionFromRequest()
#1 C:\Sviluppo\spid\server\spid-php-master\setup\simplesamlphp\simplesamlphp\lib\SimpleSAML\Error\Error.php(234): SimpleSAML\Error\Error-&gt;saveError()
#2 C:\Sviluppo\spid\server\spid-php-master\vendor\simplesamlphp\simplesamlphp\www\_include.php(18): SimpleSAML\Error\Error-&gt;show()
#3 [internal function]: SimpleSAML_exception_handler(Object(InvalidArgumentException))
#4 {main}
  thrown in <b>C:\Sviluppo\spid\server\spid-php-master\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\Session.php</b> on line <b>307</b><br />

Altre informazioni
Il web server è Apache 2 (inoltre ho verificato sul php.ini l'opzione session.cookie_secure, la quale non è impostata)  e il sistema operativo è windows 11.

Idee?

**Comment by fredericks** [comment]
Innanzitutto grazie per la risposta,.
In effetti, mettendo a false il parametro non ho più ottenuto quell'errore.

Tuttavia, da 127.0.0.1 mi dà
Warning: session_create_id(): Failed to create new ID in C:\Sviluppo\QUESTIT\spid\server\spid-php-master\vendor\simplesamlphp\simplesamlphp\lib\SimpleSAML\SessionHandlerPHP.php on line 173

Invece usando ngrok come proxy non mi dà errori. Però provando ad inserirlo qui:

![image](https://user-images.githubusercontent.com/7090975/174094923-b93d21c8-59ea-402c-879f-c8b8df473576.png)

mi dà un altro errore:

![image](https://user-images.githubusercontent.com/7090975/174094738-18ab3201-53a8-4ef4-b3f2-4d2907f1975c.png)

**Comment by damikael** [comment]
è necessario che il server sia esposto pubblicamente.
