### ISSUE TITLE
PHP 8 compatibility 

### ISSUE THREAD

**Issue by abackenddev** [italia/spid-php#170]
Buongiorno,

come da titolo vorrei chiedere come mai la libreria non è compatibile con php 8 e successive e se è già stata pianificata l'attività di aggiornamento.

Grazie

**Comment by damikael** [comment]
Buongiorno @abackenddev , 
spid-php è basato su SimpleSAMLphp 1.19.0 che indica come prerequisito PHP version >= 7.1.0
Non è detto quindi che non sia compatibile con PHP 8, ma l'installazione ed il funzionamento non sono stati mai verificati con PHP 8.
Se si vuole verificare, è possibile modificare nel file composer.json il vincolo sulla versione di PHP a:
"php": ">=7.4.1"

**Comment by damikael** [comment]
Vedi
https://github.com/simplesamlphp/simplesamlphp/issues/1521

**Comment by abackenddev** [comment]
Grazie per le informazioni. 
Sono uno sviluppatore di un'azienda che è soggetto aggregatore e ho letto che questa libreria non è orientata a questo utilizzo. L'informazione è corretta? Sarebbe possibile avere più informazioni sulla motivazione?
Grazie

**Comment by damikael** [comment]
L'implementazione del soggetto aggregatore prevede un metadata per ogni specifico soggetto aggregato con le relative sezioni ContactPerson che individuano l'aggregatore e l'aggregato (Rif. [Avviso SPID n.19 v.4](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v4-regole_tecniche_aggregatori.pdf))
La procedura di setup di spid-php, consente l'inserimento delle informazioni per la generazione di un metadata da SP, pubblico o privato, che a differenza del metadata da soggetto aggregato non contiene tali ContactPerson.
Inoltre l'implementazione del soggetto aggregatore, sia full che lite, deve consentire la creazione dell' AuthRequest in maniera dinamica e sicura in relazione allo specifico aggregato.

È possibile utilizzare spid-php per implementare una soluzione per soggetto aggregatore ma, alla versione attuale:
- i metadata per gli aggregati andrebbero creati e firmati manualmente o tramite una procedura esterna
- dovrebbe esistere una installazione dedicata di spid-php per ogni singolo soggetto aggregato, oppure si dovrebbero configurare esplicitamente gli aggregati come service nel simplesamlphp installato con spid-php
