### ISSUE TITLE
aggiornare i tpl per la creazione del bottone accedi con spid con il nuovo IDP Teamsystem

### ISSUE THREAD

**Issue by lpecorelli** [italia/spid-php#174]
Salve Michele,

ho visto che per l'aggiunta del nuovo IDP Teamsystem il progetto 

https://github.com/italia/spid-sp-access-button 

è già stato aggiornato a luglio, ma mi sembra che non sono stati aggiornati i tpl 

setup/sdk/proxy-spid.tpl
setup/sdk/proxy-spid-php.tpl

per tale aggiunta nella creazione del bottone "Accedi con SPID".

Grazie
Leonardo

**Comment by damikael** [comment]
Ciao Leonardo,
sì, a breve provvederò a rilasciare l'aggiornamento per l'IdP TeamSystem.

Grazie.
Michele D'Amico (@damikael)

**Comment by damikael** [comment]
Fixed https://github.com/italia/spid-php/commit/aca82105fa2723c060f7737718e72c56844c1db6

[Version 3.11.1](https://github.com/italia/spid-php/releases/tag/v.3.11.1)
