### ISSUE TITLE
gestione OTP di conferma per disporre operazioni rischiose

### ISSUE THREAD

**Issue by frhack** [italia/spid-php#175]
Scusate, non sono riuscito a trovare una risposta nella documentazione.

Il caso d'uso è il seguente.
Un applicazione permette di autenticare gli utenti tramite spid 2FA e una volta autenticati sono autorizzati ad una serie di funzioni.

Alcune funzioni possono essere particolarmente rischiose sotto il profilo della sicurezza e quindi per la loro esecuzione si vuole avere un' ulteriore conferma dispositiva tramite la verifica di un OTP.

Per esempio un utente accede alla applicazione tramite spid, poi si assenta dalla postazione PC e qualcuno al suo posto potrebbe eseguire tutte le funzioni senza ulteriore conferma.

Non so se è previsto dal sistema SPID a due fattori, sarebbe utile poter chiedere un OTP dispositivo per la conferma di operazioni rischiose e poterlo validare lato app tramite apposite API  spid.

Esiste questa possibilità ?

In alternativa si potrebbe ottenere questa funzionalità chiedendo all'utente di confermare l'operazione richiesta accedendo ad una seconda app di supporto che costringe quindi l'utente a ri-autenticarsi con SPID 2fa.

In alternativa ulteriore, se l'app offre solo funzioni rischiose, si puo' impostare una durata di sessione molto breve.

Ovviamente sarebbe preferibile poter gestire questo caso nativamente, quindi senza dover ricorrere allo stratagemma del doppio login.

grazie

**Comment by damikael** [comment]
Buongiorno @frhack ,
la gestione delle operazioni dispositive non è presente in SPID SAML. 
Forse potrà essere implementata in SPID OIDC tramite il meccanismo del prompt=verify (Rif. [Linee Guida OIDC SPID](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_openid_connect_in_spid.pdf)) che tuttavia, per il momento è sospesa (Rif. [Avviso SPID n.41](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n41-integrazione_ll.gg_._openid_connect_in_spid.pdf)).
Occorre tener presente che in SPID SAML non viene creata una sessione in corrispondenza di una autenticazione effettuata a livello 2 o 3, pertanto l'eventuale gestione di un meccanismo di operazioni dispositive è demandata completamente al SP. 
Ovvero il SP potrebbe:

1. gestire autonomamente la sessione utente e inviare OTP email o mobile all'utente recuperando tali dati da SPID
2. in caso di operazioni dispositive far riautenticare sempre nuovamente l'utente con SPID livello 2 o 3

Chiudo l'issue in quanto non strettamente correlata a spid-php.
Sono comunque a disposizione se occorrono eventuali ulteriori informazioni.
Mi trovi anche su [Forum Italia](https://forum.italia.it/c/spid/5) e su [Slack di Developers Italia](https://slack.developers.italia.it/)

Michele D'Amico (@damikael)
