### ISSUE TITLE
event terminated with an exception

### ISSUE THREAD

**Issue by ilsanto17** [italia/spid-php#176]
Buonasera a tutti, sto provando ad installare la libreria sul mio server locale.
Va tutto bene, ma alla fine ottengo questo errore:
`Retrieve configuration for local test IDP... Script SPID_PHP\Setup::setup handling the post-update-cmd event terminated with an exception
  [ErrorException]
  file_get_contents(y): Failed to open stream: No such file or directory`

Qualcuno sa a cosa è dovuto?
Grazie

**Comment by damikael** [comment]
Durante il setup, al prompt 
Optional URI for local Test IDP metadata (leave empty to skip) ? 
occorre indicare la URL ad un file metadata valido, oppure dare semplicemente Invio.

Michele D'Amico (@damikael)
