### ISSUE TITLE
Input sanitize for serviceName must be implemented

### ISSUE THREAD

**Issue by salvorapi** [italia/spid-php#177]
During setup process, a **serviceName** is required to define the name of the new service to install.

If you input a value separated by spaces (i.e. "my service name") or some special chars (i.e. "My $ervice/Name") then the instance doesn't work or, in some cases, the setup crash.

I think that input value must be sanitized. :) 

Salvo.

**Comment by damikael** [comment]
Good enhancement. Thanks for suggest @salvorapi

**Comment by damikael** [comment]
fixed with #178
