### ISSUE TITLE
Dopo il log in nel sito dell'IDP IDP torno indietro ma  $spidsdk->isAuthenticated() è FALSE

### ISSUE THREAD

**Issue by paolocerto** [italia/spid-php#181]
Salve,
sto provando di tutto ma non trovo una soluzione
uso spid-php all'interno di un progetto sviluppato con Laravel
Al ritorno sul mio sito dopo riconoscimento presso IDP gli unici parametri che ricevo sono in POST  e sono questi

Array
(
    [SAMLResponse] => lunga stringa codificata
    [RelayState] => altra stringa codificata
)

e $spidsdk->isAuthenticated() mi restituisce FALSE

qualcuno sa darmi qualche indicazione?
Grazie

**Comment by damikael** [comment]
Salve @paolocerto , 
puoi condividere qui o in privato il metadata da SP

**Comment by paolocerto** [comment]
Salve @damikael,
inviato email 
Grazie
