### ISSUE TITLE
errore login

### ISSUE THREAD

**Issue by ilsanto17** [italia/spid-php#183]
Buongiorno a tutti, ho bisogno urgente di supporto. Quando tento di effettuare il login in ambiente di test (SPID livello 1) ottengo questo errore:
`array(7) { ["statusCode"]=> string(44) "urn:oasis:names:tc:SAML:2.0:status:Responder" ["statusMessage"]=> string(37) "Responder/AuthnFailed: ErrorCode nr20" ["errorMessage"]=> string(91) "Utente privo di credenziali compatibili con il livello richiesto dal fornitore del servizio" ["_ga"]=> string(27) "GA1.2.1210350289.1663229193" ["_gid"]=> string(25) "GA1.2.21089457.1667395327" ["session_id"]=> string(24) "__Secure-aa2dbe2bf329c58" ["7d9642d913c6714ca4bf7d50fe037599e642fcaf"]=> string(32) "37905815dcb51fbb737c5d7923b4d78a" }`

Modificando il livello di spid (sia 2 che 3) ottengo un altro errore:
`array(7) { ["statusCode"]=> string(0) "" ["statusMessage"]=> string(67) "State not found for id _31c5fde6c43a1ca85d3fc79a210377b5db42bc804e" ["errorMessage"]=> string(23) "Errore non identificato" ["_ga"]=> string(27) "GA1.2.1210350289.1663229193" ["_gid"]=> string(25) "GA1.2.21089457.1667395327" ["session_id"]=> string(24) "__Secure-aa2dbe2bf329c58" ["7d9642d913c6714ca4bf7d50fe037599e642fcaf"]=> string(32) "37905815dcb51fbb737c5d7923b4d78a" }`

Cosa non sta funzionando??

**Comment by damikael** [comment]
Buongiorno @ilsanto17 ,
il problema è molto probabilmente legato alla perdita della sessione sul browser.
Prova a cancellare cache sul browser e rilanciare l'autenticazione a livello 2.
In ogni caso consiglio di attivare la registrazione delle sessioni di simpleSAMLphp su database, impostando nel file 
spid-php/vendor/simplesamlphp/simplesamlphp/config/config.php
le seguenti configurazioni:
```
'store.type' =>'sql'
'store.sql.dsn' => '...'
'store.sql.username' => '...',
'store.sql.password' => '...',
```

come indicato qui:
https://simplesamlphp.org/docs/stable/simplesamlphp-maintenance.html

**Comment by ilsanto17** [comment]
Grazie @damikael . risolto
