### ISSUE TITLE
Inserimento Supporto IDP TeamSystem

### ISSUE THREAD

**Issue by klu0** [italia/spid-php#184]
Buongiorno,
per aggiungere il supporto all’IDP TeamSystem ho effettuato l’aggiornamento di spid-php con i seguenti comandi:
  - composer uninstall
  - composer install

Tuttavia a seguito dell’aggiornamento, nella funzione “insertSPIDButton($size)” del file spid-php.php non era presente il codice html relativo a TeamSystem.
Per far comparire TeamSystem nell’elenco degli IDP ho dovuto quindi modificare il file spid-php.php aggiungendo il seguente codice:

```
<li class=\"spid-idp-button-link\" data-idp=\"teamsystemid\">
    <a href=\"?idp=TeamSystem s.p.a.\"><span class=\"spid-sr-only\">TeamSystem ID</span><img src=\”/[…]/spid-sp-access-button/img/spid-idp-teamsystemid.svg\" onerror=\"this.src='/[…]/spid-sp-access-button/img/spid-idp-teamsystemid.png'; this.onerror=null;\" alt=\"TeamSystem ID\" /></a>
</li>
```

Inoltre nella cartella “spid-sp-access-button\img\” ho dovuto inserire manualmente le icone di TeamSystem:
  - spid-idp-teamsystemid.svg
  - spid-idp-teamsystemid.png

Vorrei sapere se ho sbagliato qualcosa nel tentativo di aggiungere il nuovo IDP oppure se siamo di fronte ad una possibile anomalia nel codice.

Grazie

**Comment by damikael** [comment]
Buongiorno @klu0 ,

nel caso di aggiornamento a nuova versione, e non solo reinstallazione,
occorre anche scaricare nuovamente il codice. Quindi ad esempio:
- composer uninstall
- git pull
- composer install

Come solito, raccomando di eseguire prima un backup, in particolare dei file di log.
Attendo un riscontro prima di procedere a chiarire meglio anche sulla documentazione.

Michele
