### ISSUE TITLE
Non riesco ad accedere a Intesa ID

### ISSUE THREAD

**Issue by paolocerto** [italia/spid-php#187]
Buongiorno,

ho installato e configurato spid-php in una applicazione web.
Scegliendo i vari provider arrivo alla pagina di login presso il provider.
Con tutti tranne Intesa ID che mi restituisce questo

arrivo a URL
https://spid.intesa.it/Time4UserServices/services/idp/IDPUserInterface/?operation=timeout&authnRequestId=spid-php_7a782f469673e7a68b8ab29c7f4cfb29562d0f0d19
e visualizzo questo messaggio
ERROR:The remote server returned an error: (500) Internal Server Error.

Ho controllato i metadata IDP
gli URL sono corretti
https://spid.intesa.it
https://spid.intesa.it/Time4UserServices/services/idp/AuthnRequest/
https://spid.intesa.it/Time4UserServices/services/idp/SingleLogout/
e certificato è corretto

Qualcuno ha vissuto il problema? 
Grazie per l'aiuto

Paolo

**Comment by damikael** [comment]
Buongiorno Paolo, 
potrebbe essere un problema relativo alla mancata acquisizione del metadata da parte di Intesa.
Se la notifica del metadata agli IdP è avvenuta di recente suggerisco di attendere ancora qualche giorno, 
altrimenti di segnalare il problema scrivendo a spid.tech@agid.gov.it.

Michele D'Amico (@damikael)
