### ISSUE TITLE
check string, check per produzione, errore 163

### ISSUE THREAD

**Issue by SamueleDellaRocca** [italia/spid-php#188]
check string, check per produzione, errore 163
SPID Compliant Certificates Value for name attribute [Unknown OID, 2.5.4.97] must match ^(CF:IT-[a-zA-Z0-9]{16}|VATIT-\d{11})$

eseguiti  test in entrambi i modi, sia inserendo la partita iva con IT, sia senza IT

![spid-error](https://user-images.githubusercontent.com/95868858/221838099-05693503-ac26-4112-986f-d9771bdb4e00.png)

**Comment by damikael** [comment]
Buongiorno @SamueleDellaRocca,
nel caso di privato (PIVA) il certificato di produzione deve essere richiesto ad AgID inviando la CSR secondo la procedura indicata sul sito. Tale richiesta può essere fatta dopo il superamento del collaudo, per il quale non è strettamente necessario superare i test relativi al certificato, in quanto dovrà appunto essere utilizzato quello rilasciato da AgID.

[Avviso SPID n. 23 - Procedura richiesta certificati](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n23-certificati-agid-per-soggetti-spid_v.2_0.pdf)
[Avviso SPID n. 23 - Modulo richiesta di registrazione](https://www.agid.gov.it/sites/default/files/repository_files/4_spid-avviso-n23-mod.-richiesta-registrazione-allegato_1.pdf)

Ottenuto il certificato di produzione, occorre sostituirlo a quello presente nelle directory 

- spid-php/cert
- spid-php/vendor/simplesamlphp/simplesamlphp/cert

Quindi rigenerare il metadata e reinviarlo ad AgID per la pubblicazione.
