### ISSUE TITLE
Integrare nuova versione bottone SPID

### ISSUE THREAD

**Issue by damikael** [italia/spid-php#189]
Integrare la nuova versione del bottone SPID come da [Avviso SPID n. 42](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n42-spid_bottone.pdf)

**Comment by francescoscialacqua** [comment]
Ho effettuato l'aggiornamento con uninstall e install come indicato nella guida. La nuova versione sembra funzionare anche se non vedo i nuovi provider. Nel fine spid-php.php nel costruttore vedo che ci sono anche i nuovi idps ma $button_li ha solamente la vecchia lista.

**Comment by damikael** [comment]
A breve sarà rilasciata la nuova versione con l'aggiornamento dei provider.

**Comment by damikael** [comment]
Grazie @francescoscialacqua ,
per il momento l'aggiornamento del bottone con il nuovo IdP EtnaHitech era già in corso,
ma quando vuoi, puoi sempre proporre PR, ogni contributo è ben accetto.

L'aggiornamento è stato rilasciato con la versione [v.3.13.0](https://github.com/italia/spid-php/releases/tag/v.3.13.0)
Lascio l'issue aperta per l'integrazione completa del bottone dinamico.

**Comment by damikael** [comment]
Informo che è stata rilasciata la [versione v.3.15.0](https://github.com/italia/spid-php/releases/tag/v.3.15.0) che implementa l'aggiornamento dinamico del bottone.
Per aggiornare i metadata e la lista degli IdP è sufficiente:

1. aggiornare il codice di spid-php alla nuova versione
2. eseguire il comando `composer update-metadata`

Saluti
Michele D'Amico (@damikael)
