### ISSUE TITLE
SP metadata mismatch

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#19]
Il metadata del Service Provider generato da simplesamplphp è diverso da quello generato a mano con https://idp.spid.gov.it:8080/#/, le differenze sono 5:
1. quello generato da simplesamplphp ha la chiave `ds:Signature`
2. per la chiave `md:EntityDescriptor`:
   - è diverso l'attributo `protocolSupportEnumeration`, per simplesamlphp è `urn:oasis:names:tc:SAML:2.0:protocol`, mentre per idp.spi.gov.it è `urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol`
    - inoltre idp.spid.gov.it ha anche l'attributo `WantAssertionsSigned` valorizzato a `true`
3. per una delle chiavi `md:AssertionConsumerService`, idp.spid.gov.it setta l'attributo `isDefault`a `true`
4. simplesamlphp aggiunge una chiave `md:AssertionConsumerService` con attributo `Binding` valorizzato come `urn:oasis:names:tc:SAML:1.0:profiles:browser-post`
5. idp.spid.gov.it richiede una chiave `md:AttributeConsumingService` che non sapendo come impostare per ora ho settato a:
```
<md:AttributeConsumingService index="1">
  <md:ServiceName xml:lang="it">myservice</md:ServiceName>
  <md:ServiceDescription xml:lang="it"/>
  <md:RequestedAttribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
  <md:RequestedAttribute Name="fiscalNumber" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
  <md:RequestedAttribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
  <md:RequestedAttribute Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
</md:AttributeConsumingService>
```

allego i due files normalizzati con `xmlllint --format ...`:
[metadata.zip](https://github.com/italia/spid-php/files/2127318/metadata.zip)

**Comment by alexrj** [comment]
@simevo fanno fede le [Regole Tecniche](https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf), non idp.spid.gov.it. Ti consiglio di fare riferimento a quello per controllare il metadata generato da spid-php

**Comment by simevo** [comment]
l'ideale è fare uno unit test che genera il metadata e lo valida contro lo schema XSD

il metadata dell'SP ce lo produce simplesamlxml ad una url tipo: 
https://spid.simevo.com/myservice/module.php/saml/sp/metadata.php/service-l1

lo schema dovrebbe essere questo:
https://github.com/italia/spid-metadata-builder/blob/master/saml-schema-metadata-SPID-SP.xsd

e lo unit test si potrebbe fare con: https://phpunit.de/

**Comment by simevo** [comment]
ho provato con xmllint, non valida né l'uno né l'altro:
```
xmllint --debug --schema saml-schema-metadata-SPID-SP.xsd metadata_simplesamlphp.xml -noout

metadata_simplesamlphp.xml:23: element SPSSODescriptor: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor', attribute 'protocolSupportEnumeration': The value 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol' does not match the fixed value constraint 'urn:oasis:names:tc:SAML:2.0:protocol'.
metadata_simplesamlphp.xml:31: element KeyDescriptor: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}KeyDescriptor': This element is not expected. Expected is one of ( {urn:oasis:names:tc:SAML:2.0:metadata}SingleLogoutService, {urn:oasis:names:tc:SAML:2.0:metadata}NameIDFormat ).
metadata_simplesamlphp.xml fails to validate

xmllint --debug --schema saml-schema-metadata-SPID-SP.xsd metadata_idp_spid_gov_it.xml --noout

metadata_idp_spid_gov_it.xml:3: element SPSSODescriptor: Schemas validity error : Element '{urn:oasis:names:tc:SAML:2.0:metadata}SPSSODescriptor': This element is not expected. Expected is ( {http://www.w3.org/2000/09/xmldsig#}Signature ).
metadata_idp_spid_gov_it.xml fails to validate
```

**Comment by damikael** [comment]
Risolto con #43.
Il metadata generato supera i test di https://validator.spid.gov.it
