### ISSUE TITLE
Funziona tutto tranne Namirial ID

### ISSUE THREAD

**Issue by paolocerto** [italia/spid-php#190]
Buongiorno,
ho installato, configurato e integrato SPID-PHP all'interno del nostro progetto.
Funzionano tutti i Provider tranne Numirial ID
Guardando l'XML del SAML Response mi da
$xml['SAML2P:RESPONSE']['SAML2P:STATUS']['SAML2P:STATUSCODE']['VALUE'] == 'urn:oasis:names:tc:SAML:2.0:status:Success'
ma poi i dati richiesti non ci sono.
Dentro la sezione 'SAML2:ASSERTION' proprio non c'è sezione 'SAML2:ATTRIBUTESTATEMENT'
c'è però SAML:ISSUER con campo FORMAT con valore urn:oasis:names:tc:SAML:2.0:nameid-format:entity
Qualcuno può aiutarmi a capire quale può essere il problema?
Grazie per l'aiuto
Paolo

**Comment by damikael** [comment]
Buongiorno @paolocerto ,
puoi verificare se il valore specificato per AttributeConsumingServiceIndex all'interno della SAML Request corrisponde ad un indice di AttributeConsumingService presente nel metadata del tuo SP e se tale set di attributi non è vuoto.

Michele D'Amico

**Comment by paolocerto** [comment]
Buongiorno @damikael,

non ho request nei log
ma nel mio metadata ho questo <md:AttributeConsumingService index="0">

Offro un solo servizio collegato a SPID dovrei avere più indici?
Grazie per l'aiuto

Paolo

**Comment by damikael** [comment]
I log sono registrati in:
spid-php/vendor/simplesamlphp/simplesamlphp/log

oppure puoi recuperare la SAML Request attraverso un plugin del browser, ad esempio SAML Chrome Panel per Chrome.

Michele D'Amico

**Comment by paolocerto** [comment]
trovato!
Per la chiamata che ho analizzato nella request c'è questo  AttributeConsumingServiceIndex="0"

**Comment by damikael** [comment]
Confermi anche che all'interno del metadata, nel set di attributi, sono dichiarati gli attributi che intendi ricevere, come ad esempio di seguito, per ricevere Cognome, Nome e CF?

```
<md:AttributeConsumingService index="0">
   <md:ServiceName xml:lang="it">Service 0</md:ServiceName>
   <md:RequestedAttribute FriendlyName="Cognome" Name="familyName"/>
   <md:RequestedAttribute FriendlyName="Nome" Name="name"/>
   <md:RequestedAttribute FriendlyName="Codice Fiscale" Name="fiscalNumber"/>
</md:AttributeConsumingService>
```

**Comment by paolocerto** [comment]
Si
<md:RequestedAttribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="familyName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="placeOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="countyOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="dateOfBirth" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="gender" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      <md:RequestedAttribute Name="fiscalNumber" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"/>
      
Ho questi.

Paolo

**Comment by damikael** [comment]
In tal caso metadata e Request sono corretti.
Consiglio di segnalare il problema ad AgID o contattare direttamente il provider.

Saluti,
Michele D'Amico

**Comment by paolocerto** [comment]
Grazie
