### ISSUE TITLE
aggiungere `composer.lock` al repo

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#22]
secondo https://getcomposer.org/doc/01-basic-usage.md#installing-without-composer-lock:
> You should commit the composer.lock file to your project repo so that all people working on the project are locked to the same versions of dependencies (more below)."

**Comment by damikael** [comment]
Se aggiungessimo il file composer.lock, non avrebbe più senso lo script di installazione. Lo scopo invece è proprio quello di poter allestire e configurare l'ambiente simplesamlphp all'ultima versione.

**Comment by em-** [comment]
Ciao, anche io sarei interessato ad automatizzare l'installazione in modo da usarla da un `Dockerfile`. 

Avere il `composer.lock` nel repository mi sarebbe utile in modo da avere la garanzia che `composer` scarichi moduli che sono sicuro funzionino con `spid-php`, la mia paura è che nuove versioni delle dipendenze possano rompere la compatibilità in qualche modo (succede spesso).

Dal `Dockerfile` lancerei quindi `composer install`, passando in qualche modo i parametri necessari.

Per provare invece le ultime novità durante lo sviluppo invece è comodo usare `composer update` per aggiornare `composer.lock` a proprio rischio e pericolo. :D

Una opzione è che io mi porti un `composer.lock` a fianco al `Dockerfile` in modo da avere tale garanzia, ma sarebbe bello averlo direttamente in questo repository.

Ciò detto, nonostante gli sviluppatori di Composer siano oltremodo chiari sull'inclusione come riportato da @simevo, gran parte dei progetti PHP in effetti non lo include nel repository per cui boh. :(

**Comment by simevo** [comment]
la possiamo risolvere pinnando la versione di simplesamlphp nel composer.json:
```
     "require": {
-        "simplesamlphp/simplesamlphp": "*",
+        "simplesamlphp/simplesamlphp": "1.15.4"
         "italia/spid-smart-button": "*",
        "symfony/yaml": ">=3.4.11 <4.0"
```
si aggiunge allora in questo caso la dipendenza dall'estensione PHP ext-mbstring:
```
apt install php-mbstring
```
cosi facendo diventa superflua la PR #16 e possiamo chiudere anche #6
