### ISSUE TITLE
Errore convalida aggregato da portale

### ISSUE THREAD

**Issue by ddisante** [italia/spid-php#233]
Salve @damikael ,
non ho idea se dipenda dalla libreria o meno, abbiamo aperto anche una segnalazione presso il portale  "Federazione CIE".
Abbiamo configurato il tutto sia per gestire il cliente singolo che come aggregatore, relativamente alla configurazione come aggregatore quando si carica il metadata generato dal software otteniamo il seguente errore in fase di caricamento sulla piattaforma.

Grazie

![image](https://github.com/italia/spid-cie-php/assets/121808020/be4f47d7-f6b6-4601-b05d-5b315076b03e)

**Comment by damikael** [comment]
inviamelo su michele.damico@linfaservice.it

**Comment by damikael** [comment]
Risposto per email
