### ISSUE TITLE
rendere il pacchetto installabile e pubblicare su packagist

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#25]
rendere il pacchetto installabile aggiungendo il campo `name` al `composer.json` (vedi https://github.com/simevo/spid-php2/commit/5953fb838beeb7d3b1817fd9ae5023071e8a92b7)

e pubblicare su packagist, esiste già un account italia:
https://packagist.org/packages/italia/

**Comment by pdavide** [comment]
Ciao @simevo, ho creato io l'account italia per pubblicare un pacchetto al quale ho lavorato qualche tempo fa.
Se vuoi posso procedere ad aggiungere `spid-php` all'account.

**Comment by simevo** [comment]
Grazie @pdavide; aspetterei qualche settimana per avere qualcosa di più stabile, c'è parecchio da fare qui !

Per ora si possono comunque consumare con questo hack:
https://github.com/simevo/spid-wordpress/blob/master/composer.json#L5

**Comment by madbob** [comment]
C'è un motivo per cui questa issue è stata chiusa senza ulteriori commenti, ma senza la pubblicazione del pacchetto su Packagist?

**Comment by damikael** [comment]
La issue faceva riferimento ad un fork parallelo che poi è mutuato nel progetto spid-php-lib

**Comment by madbob** [comment]
Ok, grazie.
Allora ribalto la domanda: c'è un motivo per cui spid-cie-php non è su Packagist?

**Comment by damikael** [comment]
Ho provveduto ad aprire una nuova issue per seguire meglio la pubblicazione:
https://github.com/italia/spid-cie-php/issues/225
In ogni caso occorre tener presente che spid-cie-php, più che una libreria, è uno script che semplifica l'installazione e la configurazione di simpleSAMLphp, pertanto potrà essere disponibile su Packagist per il comando:
composer create-project italia/spid-cie-php
