### ISSUE TITLE
serve un tool per agevolare l'utilizzatore nel mantenimento dell'archivio dei metadata di tutti gli idp

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#28]
prototipo:
```php
<?php
// downloads the metadata for all current idps from the registry
// and stores them all in the idp_metadata directory
$idp_list_url = 'https://registry.spid.gov.it/assets/data/idp.json';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $idp_list_url);
curl_setopt($ch, CURLOPT_FAILONERROR, 1);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_TIMEOUT, 15);
echo "Contacting $idp_list_url" . PHP_EOL;
$json = curl_exec($ch);
curl_close($ch);
$idps = json_decode($json);

foreach ($idps->data as $idp) {
    $metadata_url = $idp->metadata_url;
    $ipa_entity_code = $idp->ipa_entity_code;
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $metadata_url);
    curl_setopt($ch, CURLOPT_FAILONERROR, 1);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);
    echo "Contacting $metadata_url" . PHP_EOL;
    $xml = curl_exec($ch);
    curl_close($ch);
    $file = "idp_metadata/$ipa_entity_code.xml";
    file_put_contents($file, $xml);
}
```

**Comment by damikael** [comment]
Le informazioni sui metadata sono già salvate per simplesamlphp nel file saml20-idp-remote.php.
Il comando composer update-metadata (https://github.com/italia/spid-php/issues/9) deve servire proprio ad aggiornare tali informazioni.
Quale potrebbe essere la necessità di avere un archivio metadata separato?

**Comment by simevo** [comment]
Credo di aver capito che per tutti gli SDK spid-{perl, php, python, ruby, nodejs ..} si voglia seguire l'approccio di:
1) addossare all'utilizzatore dell'SDK l'onere di mantenere **manualmente** aggiornato l'elenco degli IdP, procurandosi i loro metadati e rendendoli disponibili in una certa cartella
2) eliminare lo step di configurazione e rendere la logica di configurazione dinamica, spostandola nel costruttore della classe SPID

Ad esempio:
https://github.com/italia/spid-perl/blob/master/lib/Net/SPID.pm#L33

@alexrj confermi ?

**Comment by damikael** [comment]
@alexjr, da considerare che il comando update-metadata verrebbe richiamato manualmente dall'utilizzatore dell'SDK e, con config.yml presente, non avrebbe bisogno di ulteriori configurazioni ma inserirebbe direttamente le informazioni nel file di configurazione saml20-idp-remote.php, secondo la logica di funzionamento di simplesamlphp (https://github.com/italia/spid-php/issues/9)

**Comment by falco76** [comment]
ssp, nativamente, può aggiornare automaticamente i metadati idp utilizzando i moduli cron e metarefresh

**Comment by simevo** [comment]
https://simplesamlphp.org/docs/stable/simplesamlphp-automated_metadata

**Comment by alexrj** [comment]
@damikael La distribuzione dei metadati degli IdP ha dei requisiti di sicurezza superiori e la stiamo definendo in un altro modo. Ci sarà comunque un piccolo tool per il download; in ogni caso lo forniremo noi separatamente. I metadati scaricati saranno disponibili come file XML in una directory, quindi tutte le varie librerie che abbiamo in Developers Italia potranno limitarsi al leggere quei file.

**Comment by damikael** [comment]
Può andar bene utilizzare internamente metarefresh, comunque considerando che l'aggiornamento dei metadata deve poter essere eseguito dall'utilizzatore in modo semplice e veloce, con un semplice comando di update (come stabilito l'aggiornamento sarà manuale). Pertanto tutta la configurazione del metarefresh dovrebbe essere eseguita automaticamente in fase di installazione di spid-php.
Non mi è ancora chiara la necessità di mantenere un archivio locale dei metadata. Ad ogni modo se il tool per il download sarà fornito separatamente, questa issue si può chiudere.

**Comment by falco76** [comment]
@alexrj puoi dire di più sui requisiti di sicurezza?
credevo che l'attuale modulo metarefresh offrisse già tutte le garanzie in tema di verifica di autenticità dei metadata (fingerprint per la verifica ad esempio)

ciao

**Comment by damikael** [comment]
Al momento è possibile utilizzare il comando
composer update-metadata
