### ISSUE TITLE
testenv2 button not working

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#30]
there is an error in https://github.com/italia/spid-php/pull/8, the generated `./vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php` file has this line for the local test IdP:
```
$metadata[''] = array (
```
as a result, the link for the test idp is: `https://sp.simevo.com/myservice/module.php/saml/disco.php?entityID=https%3A%2F%2Fsp.simevo.com&return=https%3A%2F%2Fsp.simevo.com%2Fmyservice...%2526ReturnTo%253Dhttps%25253A%25252F%25252Fsp.simevo.com%25252F&returnIDParam=idpentityid&idp_=idp_`

so clicking on the link results in the idp list page to reload:

![gifrecord_2018-08-09_155102](https://user-images.githubusercontent.com/8254819/43903185-22c6ac48-9bec-11e8-8371-53d916dfc90b.gif)

this related to #21, but has a simple fix:
```
$metadata['https://sp.simevo.com'] = array (
```

**Comment by alexrj** [comment]
@simevo can you submit a Pull Request in order to fix this and any other problems you find on this software package?

**Comment by damikael** [comment]
#43 implements spid-sp-access-button
Rif. #20
