### ISSUE TITLE
dynamic SPID level switching

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#36]
currently the `AuthnContextClassRef` (SPID level) can be customized passing a parameter to the class constructor

separate SP metadata are made available for the 3 SPID levels at the `/myservice/module.php/saml/sp/metadata.php/service-l1` / `service-l2` / `service-l3` endpoints; 

for a single _real_ SP, offering 2 different SPID levels would then count as two separate SPs; this is undesirable for private SPs, as they would have to "pay twice" for each identity

SPID level switching could be made more flexible by making the package generate a single SP with one metadata for all SPID levels, and allowing to choose dynamically which SPID level to request passing a parameter to the `login` method

**Comment by damikael** [comment]
#43 solved
