### ISSUE TITLE
dynamic AssertionConsumerService/AssertionConsumerServiceIndex customization

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#37]
currently at the end of the setup:
- there are two `AssertionConsumerServices` hardcoded in the metadata
- the `AssertionConsumerServiceIndex` to submit with the `AuthnRequest` is hardcoded

provide an API for the user to:
- configure dynamically in the class constructor the `AssertionConsumerServices` that go in the metadata
- choose which `AssertionConsumerServiceInded` to submit with the `AuthnRequest` via a parameter in the `login` method

**Comment by damikael** [comment]
#43 
There is no need to configure more than one acs.
AuthnContextClassRef for SPID level can be submited as parameter in the login.
