### ISSUE TITLE
Formato richiesta non corretto - Contattare il gestore del servizio

### ISSUE THREAD

**Issue by RoBYCoNTe** [italia/spid-php#46]
Buongiorno,
dopo aver configurato correttamente il servizio ed essere riuscito ad eseguire un login utilizzando la macchina docker predisposta per i test IdP, ho tentato un login tramite servizio esterno (es. poste italiane) ma, indipendentemente dall'IdP selezionato, ottengo sempre il seguente messaggio di errore:

> Formato richiesta non corretto - Contattare il gestore del servizio

Mi sarei aspettato un messaggio che avesse a che fare con problematiche inerenti la non validità del service provider che, giustamente, in questo momento non è registrato/validato da AGID. E' normale ricevere questo errore?

**Comment by damikael** [comment]
Buongiorno,
con riferimento alla tabella dei messaggi di anomalia SPID
(https://www.agid.gov.it/sites/default/files/repository_files/regole_tecniche/spid_tabella_messaggi_di_anomalia_v1.0.pdf)
il caso è riconducibile all'Error Code 10 (_Issuer non presente_), pertanto il messaggio è conforme a quanto atteso.
