### ISSUE TITLE
Problema con logout

### ISSUE THREAD

**Issue by lellomaverick** [italia/spid-php#47]
Ciao @damikael , ho implementato la fase di login e sto facendo dei test sul logout, ma SAML va in eccezione richiamando il metodo logout().
Con il metodo getLogoutUrl() riesco a generare il link per effettuare il logout, ma al click si presenta il problema. Ho effettuato il test con Poste ID e Sielte ID e il risultato è identico.
Come posso risolvere?

**Comment by damikael** [comment]
Ciao @lellomaverick ,
il problema dovrebbe essere risolto con gli ultimi aggiornamenti.
Se hai effettuato l'installazione tramite script puoi eseguire `composer uninstall`, aggiornare i sorgenti, quindi eseguire `composer install`
