### ISSUE TITLE
Incorrect valuae of the NameID element within the LogoutRequest

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-php#48]
According to [Avviso SPID n°3](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n3-chiarimenti-sessioni-singlelogout.pdf) the value of NameID elemento must be Identity Provider's entityID

**Comment by damikael** [comment]
Per aggiornare la propria installazione:

- eseguire `composer uninstall`
- aggiornare spid-php
- eseguire `composer install`
