### ISSUE TITLE
IDP TIM exception

### ISSUE THREAD

**Issue by filippoma** [italia/spid-php#49]
salve,
ho il seguente problema con TIM dopo aver eseguito l'accesso:

![WhatsApp Image 2019-05-02 at 14 10 18 (1)](https://user-images.githubusercontent.com/30654829/57074773-31c7d080-6ce5-11e9-8d0b-34ed5274159d.jpeg)

**Comment by damikael** [comment]
Nel metadata unico di configurazione risultano presenti due certificati per TIM di cui solo il secondo valido. Il processo di configurazione, invece, configurava solo il primo certificato trovato.
L'ultima commit risolve il problema configurando in SimpleSAMLphp tutti i certificati presenti nel metadata unico di configurazione.

Se la versione dello script utilizzata è > 2.0 (il numero di versione è indicato nel file composer.json), per aggiornare la propria installazione è sufficiente eseguire:

`composer update-metadata`

**Comment by filippoma** [comment]
Grazie mille per la pronta risposta.
Volevo chiedere inoltre come intercettare queste eccezioni in modo tale da
gestire io il layout.
Grazie mille ancora

Il giorno ven 3 mag 2019 alle ore 12:06 damikael <notifications@github.com>
ha scritto:

**Comment by damikael** [comment]
La soluzione consigliata è creare un tema, come indicato nella documentazione ufficiale:
https://simplesamlphp.org/docs/stable/simplesamlphp-theming

All'interno della directory del tema, occorrerà copiare e personalizzare i file del tema di default.
In particolare il file che gestisce le schermate per le eccezioni è:
spid-php/vendor/simplesamlphp/simplesamlphp/templates/error.php

Tale file è una versione modificata da spid-php rispetto al file originale di SimpleSAMLphp per permettere la visualizzazione dei messaggi di errore relativi alle anomalie SPID anche nel caso in cui nel file di configurazione venga impostato showerrors => true (impostazione consigliata in produzione. Rif. https://github.com/simplesamlphp/simplesamlphp/blob/d0921997489791e3ef35dd70d556d4786283f79b/config-templates/config.php#L234).

Altra soluzione è intercettare gli errori con una funzione personalizzata definita tramite la variabile errors.show_function nel file di configurazione (Rif. https://simplesamlphp.org/docs/stable/simplesamlphp-errorhandling#5.5)
