### ISSUE TITLE
aggiornare spid-smart-button

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#5]
https://github.com/italia/spid-php/blob/master/composer.json#L9

punta a [damikael/spid-smart-button](https://github.com/damikael/spid-smart-button) che è "1 commit ahead, 242 commits behind italia:master"

**Comment by damikael** [comment]
Su italia/spid-smart-button è in corso di sviluppo il nuovo mockup. 
La versione damikael/spid-smart-button, invece, integra modifiche che sono funzionali a spid-php (loghi degli idp). Tali modifiche sono state proposte sulla PR https://github.com/italia/spid-smart-button/pull/17.
Non appena la PR sarà riportata su italia/spid-smart-button sarà possibile riconsiderare l'integrazione con il repository ufficiale.

**Comment by simevo** [comment]
Ok però io lascerei questa issue aperta come promemoria
