### ISSUE TITLE
SPID per persone giuridiche

### ISSUE THREAD

**Issue by lellomaverick** [italia/spid-php#50]
Buonasera a tutti, sto realizzando una piattaforma dove le aziende si candidano a sviluppare progetti sul territorio e lo SPID per persone fisiche è già attivo, ma per coerenza e motivi di sviluppo della piattaforma sarebbe meglio utilizzare lo SPID per persone giuridiche. Ho girato un pò su internet e ho visto che, per esempio, Aruba offre un servizio business, però mi chiedo se l'attuale sdk PHP di SPID funziona anche con le identità delle persone giuridiche. @damikael cosa puoi dirmi a riguardo? Scusa il leggero off-topic, ero indeciso se scrivere qui o nel forum di Agid, però penso che le informazioni che potresti darmi possono essere utili anche ad altri sviluppatori.

**Comment by damikael** [comment]
Ciao @lellomaverick ,

spid-php non è stato testato con identità SPID per persona giuridica, tuttavia, dal punto di vista di implementazione del protocollo SAML non cambia nulla. 

Occorre tenere presente che nella response ricevuta dall'IdP risulteranno valorizzati gli attributi relativi alla tipologia di identità per la quale si è eseguita l'autenticazione. Quindi, ad esempio, per persona fisica, risulteranno valorizzati gli attributi _name_ e _familyName_ e non risulterà valorizzato l'attributo _companyName_, mentre, per persona giuridica, viceversa, risulterà valorizzato l'attributo _companyName_ e non gli attributi _name_ e _familyName_.
Ciò implica che gli attributi d'interesse siano opportunamente configurati come AttributeConsumingService nel metadata. 
Poichè il processo di configurazione automatico di spid-php, attualmente, permette la configurazione di un solo AttributeConsumingService, per gestire entrambi i casi di autenticazione con una sola istanza di spid-php, e senza intervenire direttamente sulle configurazioni di SimpleSAMLphp, occorre richiedere in fase di configurazione tutti gli attributi utili per entrambi i casi e demandare all'applicazione la verifica della tipologia di utenza sulla base dei valori ricevuti.

**Comment by damikael** [comment]
Con l'avviso [SPID n.18 v.2](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf) per ottenere i dati dell'identità digitale persona giuridica, occorre effettuare la richiesta di autenticazione con l'estensione Purpose valorizzata a LP o PX.
Con la versione [3.4.0](https://github.com/italia/spid-php/releases/tag/v.3.4.0) è possibile utilizzare la funzione [setPurpose](https://github.com/italia/spid-php#setpurpose) per inviare la richiesta di autenticazione con l'estensione corretta.
