### ISSUE TITLE
Personalizzazione schermate di errore

### ISSUE THREAD

**Issue by damikael** [italia/spid-php#55]
Per personalizzare le schermate di errore standard di SimpleSAMLphp, la soluzione consigliata è creare un tema, come indicato nella documentazione ufficiale:
https://simplesamlphp.org/docs/stable/simplesamlphp-theming

All'interno della directory del tema, occorrerà copiare e personalizzare i file del tema di default.
In particolare il file che gestisce le schermate per le eccezioni è:
spid-php/vendor/simplesamlphp/simplesamlphp/templates/error.php

Tale file è una versione modificata da spid-php rispetto al file originale di SimpleSAMLphp per permettere la visualizzazione dei messaggi di errore relativi alle anomalie SPID derivanti dall'utente (https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/messaggi-errore.html) anche nel caso in cui nel file di configurazione venga impostato **showerrors => false** (impostazione consigliata in produzione. Rif. https://github.com/simplesamlphp/simplesamlphp/blob/d0921997489791e3ef35dd70d556d4786283f79b/config-templates/config.php#L234).

Altra soluzione è intercettare gli errori con una funzione personalizzata definita tramite la variabile errors.show_function nel file di configurazione (Rif. https://simplesamlphp.org/docs/stable/simplesamlphp-errorhandling#5.5)

**Comment by DiFioriTiziano** [comment]
Salve questo vale anche nel caso di simulazione di response errata su Login?
stiamo sviluppando un autenticazione come SP.
per ora usiamo l ambiente di test idptest
in  caso di login positivo non abbiamo problemi, 
ma quando simuliamo un errore, 
e quindi eseguiamo  anche i test :
- Destination errata
- Audience errata
verificando che l' implementazione rigetti la risposta.
ci ritorna la classica pagina di simplesamlphp di errore
**SimpleSAML_Error_Error: UNHANDLEDEXCEPTION**

vorremmo solo che invece di quella pagina ci tornasse una pagina personalizzata
dove dovremmo intervenire?

**Comment by damikael** [comment]
È sufficiente modificare il file 
`spid-php/vendor/simplesamlphp/simplesamlphp/templates/error.php`

**Comment by andreakappa** [comment]
Noi abbiamo fatto come suggerito da @damikael e con la pagina custom ci siamo, tuttavia abbiamo visto che i messaggi di errore arrivano in inglese, senza possibilitá di abilitarne la localizzazione italiana (nel codice si SimpleSAMLphp non c'é nemmeno la chiamata a gettext attorno a quelle stringhe. Voi come avete fatto?

**Comment by damikael** [comment]
Salve @andreakappa ,
i messaggi di errore, relativi alle anomalie utente, ovvero gli unici che devono essere presentati a video in maniera esplicita, sono già in lingua italiana, disponibili nel file error.php tramite:

`$this->data['errorMessage']`

Tutti gli altri errori, per i quali errorMessage non è definito oppure è vuoto, possono essere mostrati con un messaggio generico del tipo "Si è verificato un errore durante l'autenticazione SPID. Riprovare".

**Comment by damikael** [comment]
Rif. #151
