### ISSUE TITLE
Problema con IdP Aruba

### ISSUE THREAD

**Issue by lellomaverick** [italia/spid-php#57]
Buongiorno @damikael ,
un utente ha effettuato il login su Aruba e la libreria SAML va in eccezione. Di seguito il messaggio di errore:

www/_include.php:17 (SimpleSAML_exception_handler)
[builtin] (N/A) Caused by: SimpleSAML_Error_Exception: state not found for ID spid-php__stringalfanumerica_
_pathinstallazione_/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Message.php:607 (sspmod_saml_Message::processResponse)
modules/saml/www/sp/saml2-acs.php:129 (require)
www/module.php:135 (N/A)

Ho provato Poste Italiane con le mie credenziali e non rilevo nessun problema. Mi puoi aiutare?

**Comment by damikael** [comment]
Il problema può verificarsi nel caso in cui si perde la sessione sul SP durante l'autenticazione presso l'IdP (ad esempio cancellazione cookie o timeout SP), per cui nel momento in il flusso torna sul SP non si riesce a recuperare la sessione collegata alla richiesta di autenticazione.
Il problema non dovrebbe essere sistematico. Si potrebbe, pertanto, gestire il caso di errore, invitando l'utente a riprovare l'autenticazione.
