### ISSUE TITLE
Class DOMDocument not found

### ISSUE THREAD

**Issue by marcosantacroce** [italia/spid-php#59]
Nella visualizzazione del metadata attraverso il link /module.php/saml/sp/metadata.php/service non ottengo niente.
Nel file di log mi riporta il seguente errore
SimpleSAML_Error_Exception: Error 1 - Class 'DOMDocument' not found
/usr/local/spid-php/vendor/simplesamlphp/simplesamlphp/www/_include.php:58 (SimpleSAML_error_handler)
/usr/local/spid-php/vendor/simplesamlphp/simplesamlphp/www/_include.php:26 (SimpleSAML_exception_handler)

**Comment by damikael** [comment]
Provare a rieseguire la procedura di installazione facendo
```
composer uninstall
composer install
```

e assicurarsi che non vengano riscontrati errori durante lo script di installazione

**Comment by marcosantacroce** [comment]
L'ho fatto ma ottengo lo stesso risultato

**Comment by marcosantacroce** [comment]
Durante l'installazione compaiono i seguenti avvertimenti:
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package jaimeperez/twig-configurable-i18n is abandoned, yiou should avoid using it. Use simplesamlphp/twig-configurable-i18n instead.

**Comment by damikael** [comment]
Controlla che siano installate sul sistema le dipendenze:
php-xml
php-mbstring

**Comment by marcosantacroce** [comment]
Si sono installate

**Comment by marcosantacroce** [comment]
Ho risolto. Non mi ero accorto che Apache utilizza il vecchio php 7.0, mentre io facevo riferimento a php 7.3
Modificato il phph in apache funziona tutto.
Grazie.
