### ISSUE TITLE
Sessioni php

### ISSUE THREAD

**Issue by marcosantacroce** [italia/spid-php#63]
Scusa forse la domanda banale, ma mi puoi spiegare come utilizzare le sessioni php specifiche dell'applicazione.
Se provo ad utilizzarle il framework me le cancella, da come ho potuto leggere.

**Comment by damikael** [comment]
Sulla documentazione ufficiale di SimpleSAMLphp è indicato come utilizzare correttamente le sessioni:
https://simplesamlphp.org/docs/development/simplesamlphp-sp-api
