### ISSUE TITLE
AuthnRequest/NameIDPolicy - attribute: AllowCreate

### ISSUE THREAD

**Issue by voidloop** [italia/spid-php#65]
Salve, 

sto provando a configurare spid-php utilizzando come "local test idp" il software spid-testenv2. Ottengo questo messaggio di errore:

```
AuthnRequest/NameIDPolicy - attribute: AllowCreate | item not allowed
```
L'AuthnRequest generato da spid-php è il seguente (ho nascosto alcune url): 

```
<samlp:AuthnRequest
    xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="spid-php_f955504a95032dcd22d5f11eaa7b5d26f3e4cb098b" Version="2.0" IssueInstant="2021-02-11T10:55:10Z" Destination="https://XXXXXX" ForceAuthn="true" AssertionConsumerServiceURL="http://localhost/spid/module.php/saml/sp/saml2-acs.php/service" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AttributeConsumingServiceIndex="0">
    <saml:Issuer NameQualifier="https://XXXXXX" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://XXXXXX</saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" AllowCreate="true"/>
    <samlp:RequestedAuthnContext Comparison="exact">
        <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>
        <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL2</saml:AuthnContextClassRef>
        <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL3</saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
Come mai spid-php inserisce in NameIDPolicy l'attributo AllowCreate="true"? 

Come posso risolvere?

Grazie

**Comment by damikael** [comment]
È un errore, in accordo con l'[Avviso SPID n.5](https://www.agid.gov.it/sites/default/files/repository_files/documentazione/spid-avviso-n5-regole-tecniche-errata-corrige.pdf) , l'attributo AllowCreate deve essere eliminato.
Grazie @voidloop per la segnalazione, appena possibile provvederò ad aggiornare.

**Comment by damikael** [comment]
@voidloop non ricordavo, in effetti spid-php già applica questa specifica:
https://github.com/italia/spid-php/blob/6e0d93582a56427f48fd6817a10fd79e0b97a39a/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php#L227
L'installazione è stata eseguita tramite composer da linea di comando come indicato in README ?

**Comment by voidloop** [comment]
Ciao @damikael, sì per farlo funzionare nella mia copia locale ho commentato queste tre linee:

https://github.com/italia/spid-php/blob/6e0d93582a56427f48fd6817a10fd79e0b97a39a/setup/simplesamlphp/saml2/src/SAML2/AuthnRequest.php#L729-L731

**Comment by voidloop** [comment]
@damikael scusami, ho nuovamente clonato il progetto e ora sembra che tutto funzioni correttamente. Non vorrei aver fatto qualche stupidaggine. Grazie per la pazienza!
