### ISSUE TITLE
ContactPerson contactType="billing"

### ISSUE THREAD

**Issue by filippoma** [italia/spid-php#66]
Salve, 
c'è la possibilità di inserire i dati per il billing  attraverso la configurazione del composer come richiesto dalle seguenti specifiche:

https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati_0.pdf

Grazie mille

**Comment by damikael** [comment]
Buongiorno,
la feature è prevista tra gli sviluppi futuri.

**Comment by filippoma** [comment]
Ho implementato la parte mancante ora il metadata viene generato con i parametri mancanti, per attivare la login per uso professionale devo mettere a true Professional use? 
$spidsdk->setProfessionalUse(true);

**Comment by damikael** [comment]
> Ho implementato la parte mancante ora il metadata viene generato con i parametri mancanti

Ottimo, se vuoi puoi condividere il tuo contributo e aprire una PR.

> per attivare la login per uso professionale devo mettere a true Professional use?

sì, specificando setProfessionalUse(true) la request di autenticazione viene costruita specificando l'extension per l'uso professionale. Al momento viene gestito esclusivamente l'attributo P (Uso professionale persona fisica)

Rif: [Avviso SPID n.18v.2](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf)

**Comment by damikael** [comment]
La versione 3.1 introduce la generazione del metadata per SP Privati.
