### ISSUE TITLE
Errore generazione certificato

### ISSUE THREAD

**Issue by paoloveggi** [italia/spid-php#67]
Salve a tutti,

dopo aver compilato correttamente, a mio avviso, i dati richiesti in fase di installazione (ultima release disponibile) vedo sul terminale il seguente errore:

problems making Certificate Request
140358896793488:error:0D06407A:asn1 encoding routines:a2d_ASN1_OBJECT:first num too large:a_object.c:108:
140358896793488:error:0B083077:x509 certificate routines:X509_NAME_ENTRY_create_by_txt:invalid field name:x509name.c:295:name=organizationIdentifier

Ho verificato e l'identifier della mia PA è corretto, ma nella cartella cert/ trovo solo il file .pem e non il certificato.

Qualcuno ha idee su come risolvere?

Grazie.

**Comment by webcox** [comment]
Mi accodo, stesso identico errore.

**Comment by p4ever** [comment]
stesso identico problema, sfortunatamente non ho modo di aggiornare openssl in quanto su CentOS 7, ma lo stesso identico si presenta anche su macOS.

Quello che ho trovato è che potrebbe essere una richiesta malformata nella generazione del certificato
https://stackoverflow.com/questions/64033765/openssl-first-num-too-large-what-does-it-mean-and-how-to-have-it-fixed

**Comment by webcox** [comment]
> 
> 
> stesso identico problema, sfortunatamente non ho modo di aggiornare openssl in quanto su CentOS 7, ma lo stesso identico si presenta anche su macOS.
> 
> Quello che ho trovato è che potrebbe essere una richiesta malformata nella generazione del certificato
> https://stackoverflow.com/questions/64033765/openssl-first-num-too-large-what-does-it-mean-and-how-to-have-it-fixed

Ho aggiornato ad openssl 1.1.1 su Centos 7.9, Si può fare
