### ISSUE TITLE
Librerie abbandonate in fase di installazione

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#68]
Durante l'installazione tramite composer emergono queste 2 librerie
  - Installing twig/extensions (v1.5.4): Extracting archive
  - Installing jaimeperez/twig-configurable-i18n (v1.2): Extracting archive

con relativo warning
Package jaimeperez/twig-configurable-i18n is abandoned, you should avoid using it. Use simplesamlphp/twig-configurable-i18n instead.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.

Spero sia di aiuto

**Comment by damikael** [comment]
E' previsto l'adeguamento all'ultima versione di SimpleSAMLphp. Con l'adeguamento si provvederà a verificare anche le dipendenze obsolete.

Grazie per la segnalazione
