### ISSUE TITLE
Mancano elementi determinati dall'avviso 25

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#69]
E' ancora presente il campo "address" e mancano i nuovi campi determinati dall'avviso 25
https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n25-nuova-codifica-domicilio_fisico.pdf

Tale avviso emanato il 27 maggio 2020 disponeva anche che a un certo punto non meno di 8 mesi dopo cesserà l'uso del campo address... Vero è che gli IdP non hanno minimamente implementato il nuovo set di campi, ma credo sarebbe doveroso aggiornare la libreria per includerli

**Comment by damikael** [comment]
La versione 3.3.0 introduce i nuovi attributi per il domicilio.
https://github.com/italia/spid-php/releases/tag/v.3.3.0
