### ISSUE TITLE
configurazione di un nuovo idp

### ISSUE THREAD

**Issue by simevo** [italia/spid-php#7]
a scopo di test ho un idp testenv2

come faccio a configurare spid-php in modo che:
1. mostri solo quell'idp (vedi anche [qua](https://github.com/italia/spid-smart-button/issues/14#issuecomment-397087972))
2. si integri con quell'idp: ho generato il metadata.xml, dove lo devo mettere per darlo in pasto a spid-php ?

**Comment by damikael** [comment]
Essendo basato su simplesamlphp, gli idp da mostrare e le informazioni dei relativi metadata vanno configurati in:
spid-php/vendor/simplesamlphp/simplesamlphp/metadata/saml20-idp-remote.php
