### ISSUE TITLE
Suggerimenti per CSS e JS

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#70]
## CSS
Ho notato un errore nel CSS del pulsante
`.spid-idp-button .spid-idp-button-menu li > a img`
c'è un `padding: 10px 0 10px 10px` che invece andrebbe posizionato non all'immagine ma al tag A
`.spid-idp-button .spid-idp-button-menu li > a`
Come potete notare dall'immagine il CSS originale rende le icone minuscole
![image](https://user-images.githubusercontent.com/6317497/108328749-42ed1480-71cd-11eb-8f93-e845d2439666.png)
Coon la modifica diventa
![image](https://user-images.githubusercontent.com/6317497/108330254-b42cc780-71cd-11eb-8508-e8c98c761eda.png)

## JS
la chiamata `insertSPIDButtonJS()` inserisce un jquery obsoleto senza controllare se un altro JQuery è già presente.
Questo rende l'integrazione in progetti esistenti che hanno già bootstrap e jquery con plugin impossibile!

**Comment by damikael** [comment]
Buongiorno @deligant ,

css e js del bottone vengono recuperati in fase di installazione dal repository ufficiale del bottone classico spid:
https://github.com/italia/spid-sp-access-button

Anche il codice javascript che viene realizzato da spid-php è comunque lo stesso indicato per il bottone ufficiale.
I problemi di css, invece, si verificano come conflitto in presenza di Bootstrap.
Non è quindi un problema strettamente correlato al presente repository.

In ogni caso ritengo utile intervenire direttamente su spid-php.
Riguardo alla versione di jquery, con il prossimo rilascio, renderò opzionale l'inserimento di jquery incluso nel pulsante ufficiale.

Michele

**Comment by deligant** [comment]
Grazie per la prontissima risposta!
sto lavorando su un CSS aggiuntivo per adeguare il pulsante a un eventuale menu in bootstrap (chiamandolo con "BS") così che mantenga il look and feel del sito e rispetti quello del bottone ufficiale

**Comment by damikael** [comment]
Ottimo, puoi crearlo come file custom.css e potremo incorporarlo in setup/www/css

**Comment by damikael** [comment]
@deligant quando avrai la modifica pronta, puoi aprire PR.
Grazie
