### ISSUE TITLE
Procedura installazione sbaglia i link del pulsante

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#71]
Ho notato che la procedura di installazione, dopo aver fatto richieste varie tra cui il la root del web server e la directory dove inserire il servizio, poi "trasforma" la classe insernedo "hardcoded" solo il servizio ma senza tenerne conto nel JS dei pulsanti di dove si trova quel servizio... e neppure quale sia il webserver associato...
Suggerisco pertanto di chiedere all'installazione una nuova variabile `baseUrl` da valorizzare con il webserver dove sarà il servizio (con slash finale), registrarla nel config e usare nella __construct della classe il costrutto `$this->WebPath=$config['baseUrl'].$config['baseurlpath']`, e sostituendo nel template `{{SERVICENAME}}` con `$this->WebPath` rendendo poi inutili l'hardcoding delle varie variabili nella "rigenerazione" della classe.
Questo permetterebbe a piattaforme complesse che agiscono su più sottodomini ma permettendo a un utente di autenticarsi una sola volta di avvalersi del pulsante su ognuno dei sottodomini rimandando sempre allo stesso servizio.

**Comment by damikael** [comment]
Buongiorno @deligant ,
grazie per il suggerimento. Se vuoi puoi proporre PR.

Michele

**Comment by deligant** [comment]
Provvederò a mandare una PR appena sistemate un po' di cose.

**Comment by damikael** [comment]
Grazie, attendo PR
