### ISSUE TITLE
Richiesta OrganizationType setup

### ISSUE THREAD

**Issue by AlessandraB19** [italia/spid-php#72]
Al momento del setup, nella richiesta "Is a Public Administration" pur inserendo N, trattandosi nel mio caso di un'organizzazione privata, ritrovo nel file di setup generato "spIsPublicAdministration":true. 
Sono stati apportati cambiamenti?
In setup eseguiti precedentemente non ho riscontrato questo problema

**Comment by damikael** [comment]
Sì, è stata cambiata la logica. Ti consiglio di utilizzare l'ultima versione rilasciata pochi minuti fa  (v.3.1.1)
https://github.com/italia/spid-php/releases/tag/v.3.1.1
che aggiunge nel metadata le info relative alla fatturazione secondo Avviso SPID n.29 v.3
