### ISSUE TITLE
Errore validazione login

### ISSUE THREAD

**Issue by AlessandraB19** [italia/spid-php#74]
In seguito ad una richiesta di autenticazione ricevo il seguente errore, con dettagli di cui non ho alcun riscontro. Di seguito uno stralcio 

EntityDescriptor/SPSSODescriptor/KeyDescriptor/0/KeyInfo/X509Data/X509Certificate/text | not a valid value-----BEGIN CERTIFICATE----- MIIDyTCCArGgAwIBAgIULp5LfDlzGGS9W4cnRiCQagKhV0kwDQYJKoZIhvcNAQEL BQAwdDELMAkGA1UEBhMCSVQxCzAJBgNVBAgMAlBDMQ8wDQYDVQQHDAZBbHNlbm8x.....DnfPFzZeg==
-- | --
/md:EntityDescriptor/md:SPSSODescriptor/md:KeyDescriptor[1]/ds:KeyInfo/ds:X509Data/ds:X509Certificate | Element 'X509Certificate': ['MIIDyTCCArGgAwIBAgIULp5LfDlzGGS9W4cnRiCQagKhV0kwDQYJKoZIhvcNAQELBQAwdDELMAkG1UEBhMCSVQxCzAJBgNVBAgMAlBDMQ8wDQYDVQQHDA....Rwev+mnnPyJ2S7kUoAAd+DlH9GHMbgoxrwm05uDIYYuxLPlO3fOx4qwVo0WQMw97gvT/JFRMm4HrQzaTakw55YhcL4VkcM+wiKUhij/+vDMrfnmDDn39vmF68/E/4DTdK3kEmd1rDnfPFzZeg=='](url) is not a valid value of the atomic type 'xs:base64Binary'.
![Cattura](https://user-images.githubusercontent.com/78797100/108353550-93be3680-71e8-11eb-8242-76f8a554d24e.PNG)

**Comment by damikael** [comment]
È probabile che l'errore fosse correlato all'idp di test piuttosto che alla generazione della request.
Se il problema dovesse persistere invito ad aprire una nuova issue.
Grazie.
