### ISSUE TITLE
Autenticazione non riuscita (spid-testenv2)

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#75]
Provando ad autenticarmi con lo spid-testenv2 ricevo questo errore
![image](https://user-images.githubusercontent.com/6317497/108373773-8b71f580-7200-11eb-97b8-a1b135604d8c.png)

**Comment by damikael** [comment]
Probabilmente si sta utilizzando una versione precedente,
il problema non dovrebbe essere presente con l'ultima versione.

**Comment by deligant** [comment]
La versione di spid-testenv2 è quella di github master aggiornata a pochi secondi fa, stesso errore.

C'è tuttavia da dire che al momento di fare il redirect all'idp "locale" (in realtà sta su un altro server) nel browser compare un errore. cercherò di intercettarlo poi ti faccio sapere.

**Comment by damikael** [comment]
Intendevo che probabilmente si sta utilizzando una versione precedente di spid-php

**Comment by deligant** [comment]
spid-php aggiornato ad adesso.

L'errore recuperato dal /var/log/php/php_error.log è il seguente

PHP Warning:  openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended in [...]/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php on line 31
PHP Stack trace:
PHP   1. {main}() [...]/spid-php/vendor/simplesamlphp/simplesamlphp/www/module.php:0
PHP   2. require() [...]/spid-php/vendor/simplesamlphp/simplesamlphp/www/module.php:135
PHP   3. sspmod_saml_Auth_Source_SP->startSSO($idp = *uninitialized*, $state = *uninitialized*) [...]/spid-php/vendor/simplesamlphp/simplesamlphp/modules/saml/www/sp/discoresp.php:28
PHP   4. sspmod_saml_Auth_Source_SP->startSSO2($idpMetadata = *uninitialized*, $state = *uninitialized*) [...]/spid-php/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:356
PHP   5. sspmod_saml_Auth_Source_SP->sendSAML2AuthnRequest($state = *uninitialized*, $binding = *uninitialized*, $ar = *uninitialized*) [...]/spid-php/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:318
PHP   6. SAML2\HTTPRedirect->send($message = *uninitialized*) [...]/spid-php/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:334
PHP   7. SAML2\HTTPRedirect->getRedirectURL($message = *uninitialized*) [...]/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php:82
PHP   8. openssl_encrypt(*uninitialized*, *uninitialized*, *uninitialized*) [...]/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php:31

**Comment by gdiodato** [comment]
Buongiorno, ho aggiornato anche io spid-testenv2 e non riesco più a loggarmi da ieri.

**Comment by deligant** [comment]
Intanto ho risolto il problema legato all'errore (warning) per mancata valorizzazione del vettore.
sono 3 file da modificare nello stesso identico modo
- spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPArtifact.php riga 53
- spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php riga 28
- spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php riga 31

La modifica è la seguente ed è identica per tutti e 3
### prima
`$relayState = base64_encode(openssl_encrypt($encryptedRelayState, "aes-256-cbc", $message->getId()));`

### dopo
`$iv = openssl_random_pseudo_bytes(16);`
`$relayState = base64_encode(openssl_encrypt($encryptedRelayState, "aes-256-cbc", $message->getId(), 0, $iv));`

**Comment by deligant** [comment]
Per l'errore in testenv2 invece ho trovato questo post
https://github.com/italia/spid-testenv2/issues/235

Se corrisponde al vero abbiamo un problema: l'attributo AllowCreate è davvero non più supportato dalla documentazione ufficiale dello SPID? Se così fosse bisogna rivedere la libreria per non inserirlo più nelle chiamate!

**Comment by damikael** [comment]
Riguardo all'attributo AllowCreate già non viene più inserito:
Rif. https://github.com/italia/spid-php/issues/65

**Comment by deligant** [comment]
Allora non capisco... inserendo il pulsante e cliccando su un provider qualunque atterro su questa pagina
![image](https://user-images.githubusercontent.com/6317497/108393521-07c20400-7214-11eb-9ebc-783f605191b4.png)

Quindi andando a selezionare (di nuovo) il provider locale genera una richiesta in cui il parametro AllowCreate è presente e valorizzato a true
![image](https://user-images.githubusercontent.com/6317497/108393745-3fc94700-7214-11eb-8a0a-7cde3af8075f.png)

Tra l'altro non capisco per quale motivo si debba passare per la pagina in questione...

**Comment by damikael** [comment]
Infatti non sta funzionando correttamente.
Come è stata eseguita l'installazione?

**Comment by deligant** [comment]
ho seguito le indicazioni del readme, facendo le modifiche segnalate in altri post perché il pulsante integrato vanilla non portava da nessuna parte.
Ho fatto in modo che i link del pulsante integrato adesso mi portino a una pagina specifica, 

![image](https://user-images.githubusercontent.com/6317497/108479202-b8bcb300-7295-11eb-8565-a990eff897f2.png)

ma anche inserendo nella chiamata a login il terzo parametro il "destination" dell'identity provider mi riporta sempre alla module.php 
![image](https://user-images.githubusercontent.com/6317497/108478776-33d19980-7295-11eb-991a-2c947eb495c5.png)
generando tra l'altro parecchi errori
![image](https://user-images.githubusercontent.com/6317497/108479011-7bf0bc00-7295-11eb-9d15-72def091259d.png)

**Comment by AlessandraB19** [comment]
> Intanto ho risolto il problema legato all'errore (warning) per mancata valorizzazione del vettore.
> sono 3 file da modificare nello stesso identico modo
> 
> * spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPArtifact.php riga 53
> * spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php riga 28
> * spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php riga 31
> 
> La modifica è la seguente ed è identica per tutti e 3
> 
> ### prima
> `$relayState = base64_encode(openssl_encrypt($encryptedRelayState, "aes-256-cbc", $message->getId()));`
> 
> ### dopo
> `$iv = openssl_random_pseudo_bytes(16);`
> `$relayState = base64_encode(openssl_encrypt($encryptedRelayState, "aes-256-cbc", $message->getId(), 0, $iv));`

Ho riscontrato lo stesso problema ma dopo aver apportato le modifiche suggerite riscontro un nuovo problema
PHP Warning:  session_id(): Cannot change session id when headers already sent in 																										/home/spid/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 191, referer: https://spid.composingstudio.com/myservice/module.php/core/frontpage_auth.php
PHP Warning:  session_cache_limiter(): Cannot change cache limiter when headers already sent in 																									/home/spid/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 115, referer: https://spid.composingstudio.com/myservice/module.php/core/frontpage_auth.php
PHP Warning:  session_cache_limiter(): Cannot change cache limiter when headers already sent in 																										/home/spid/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 117, referer: https://spid.composingstudio.com/myservice/module.php/core/frontpage_auth.php
PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in 																										/home/spid/spid-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 243, referer: https://spid.composingstudio.com/myservice/module.php/core/frontpage_auth.php

Ci sono suggerimenti a riguardo?

**Comment by damikael** [comment]
Verificare se i problemi si presentano ancora utilizzando l'ultima versione, seguendo la procedura di installazione.
Nel caso venissero ancora riscontrati errori invito ad aprire una nuova issue.
