### ISSUE TITLE
Passaggio da disco.php?

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#76]
Cercando di autenticarsi via il pulsante integrato si arriva alla pagina di test di saml, che ha un errore sul path delle immagini
![image](https://user-images.githubusercontent.com/6317497/108374168-f3c0d700-7200-11eb-9336-30db28264fbe.png)
Infatti va a cercare
/myservice/spid-idp-dummy.svg
per ognuno dei service, nonostante siano configurati correttamente (e infatti il bottone integrato espanso fa vedere le icone corrette)
![image](https://user-images.githubusercontent.com/6317497/108374620-72b60f80-7201-11eb-8218-bf4ebf866aa8.png)

**Comment by damikael** [comment]
Non occorre passare dal discovery. I pulsanti devono essere implementati in modo tale da eseguire direttamente la funzione di login con il relativo idp (vedi esempi di integrazione in README)
