### ISSUE TITLE
Errore di indice inesistente in SAMLBuilder.php

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#77]
riga 745 del file
setup/simplesamlphp/simplesamlphp/lib/SimpleSAML/Metadata/SAMLBuilder.php
provoca un errore

risolvibile sostituendo la riga subito sotto il commento
`        // SPID Avviso n.29 v.3 - Private`

con
`        if(!empty($details['fpa'])) {`

**Comment by damikael** [comment]
Verificare se l'errore si presenta ancora utilizzando l'ultima versione.
Nel caso, invito ad aprire una nuova issue.
