### ISSUE TITLE
Versione di SimpleSAMLphp troppo vecchia

### ISSUE THREAD

**Issue by deligant** [italia/spid-php#78]
Forse ho trovato il motivo del perché ci sono tutti questi errori e warning e malfunzionamenti...

![image](https://user-images.githubusercontent.com/6317497/108388111-97fd4a80-720e-11eb-93b8-901b686f14ee.png)

Qui però non ho una soluzione...

**Comment by damikael** [comment]
Bisognerà indirizzare l'ultima versione di SimpleSAMLphp nel file di composer, 
ma prima di aggiornare occorre ricostruire tutte le patch, a partire dalle nuove versioni dei file

**Comment by StefSoge** [comment]
Buongiorno,

mi sono messo ad implementare lo SPID sulle mie procedure PHP da pochi giorni ed ho approfittato di tutto il lavoro trovato nel repository spid-php e spid-testenv2 oltre che, chiaramente, quello della implementazione simplesamlphp  ... e ringrazio tutti ... 

per ottenere un tree utilizzabile, aggiornato (all'ultima stabile 1.19.1) e libero da composer, che per vari motivi non amo, ho fatto i seguenti passi che riassumo di seguito per opportuna  condivisione e per capire se mi sono scordato oppure ho mal compreso qualcosa ...

1) installazione dell'ultima stabile di simplesamlphp sul mio web server ..
2) copiati i file di configurazione generati con composer nel tree di simplesaml 

a questo punto, testando l'SP con spid-testenv2 ottenevo i segueti errori di validazione:

AuthnRequest/Issuer - attribute: NameQualifier	required key not provided
AuthnRequest/Issuer - attribute: Format	required key not provided
AuthnRequest/RequestedAuthnContext - attribute: Comparison	required key not provided

ed ho adottato le seguenti soluzioni:

3) ho settato a true  $Saml2IssuerShowAll = true in     Issuer.php (grazie a @falco76 https://github.com/simplesamlphp/saml2/pull/94);
4) patchato SP.php in questa maniera:

nella funzione startSSO2 (verso riga 700) ho inserito:

`
$ar->setDestination($dst['Location']);
                                /* SPID CUSTOM  per 1.19*/ 
                               $issuer = new \SAML2\XML\saml\Issuer();
                               $issuer->setValue($this->metadata->getString('entityid'));
                               $issuer->setNameQualifier($this->metadata->getString('entityid'));
                               $ar->setIssuer($issuer);      
                               /* END SPID CUSTOM  per 1.19*/
         
 $b = Binding::getBinding($dst['Binding']);
`

e per il logout ... fun startSLO2 (verso riga 1100)

`
$b = Binding::getBinding($endpoint['Binding']);
        
                                    /* SPID CUSTOM  per 1.19*/ 
                                    $issuer = new \SAML2\XML\saml\Issuer();
                                    $issuer->setValue($this->metadata->getString('entityid'));
                                    $issuer->setNameQualifier($this->metadata->getString('entityid'));
                                    $lr->setIssuer($issuer);   
                                    /* END SPID CUSTOM  per 1.19*/ 
        
        $b->send($lr);

`

5) ho modificato nell file di configurazione authsources:
`  'AuthnContextComparison' => 'better',`
con exact sembra non passi attribute: Comparison 

Fatto questo l'SP in 1.19 chiede correttamente l'autenticazione  all'IDP  testenv2, riceve i dati di autenticazione ed effettua il logout ...

Ripeto, non avendo conoscenza approfondita del saml, ed avendo molte perplessità sul punto 5) relativo a AuthnContextComparison' => 'better'..  approfitto anche per chiedere il vostro parere .... 

GoodWork!
 
PS. mi scuso per la pessima formattazione di questo post ...

**Comment by voidloop** [comment]
S

> Bisognerà indirizzare l'ultima versione di SimpleSAMLphp nel file di composer,
> ma prima di aggiornare occorre ricostruire tutte le patch, a partire dalle nuove versioni dei file

Quanto tempo ci vorrà? La versione in uso di simplesamlphp (1.16) ha da problemi di sicurezza.

**Comment by voidloop** [comment]
Ho creato una pull request di spid-php con simplesamlphp 1.19.0. 

https://github.com/italia/spid-php/pull/83

Dovrei aver riportato tutte le patch, inoltre ho fatto delle piccole correzioni per eliminare alcune warning.

**Comment by damikael** [comment]
Rilasciata nuova versione con le modifiche proposte.
Grazie @voidloop
