### ISSUE TITLE
Generazione metadata con più AssertionConsumerService e SingleLogoutService

### ISSUE THREAD

**Issue by gianusa** [italia/spid-php#80]
Buongiorno,
dovrei aggiornare  un metadata già registrato in Agid aggiungendo un nuovo tag AssertionConsumerService e un nuovo tag SingleLogoutService .
L'implementazione attuale però sembra poter generare un singolo AssertionConsumerService.
E' possibile gestire questo caso con la libreria spid-php?
Grazie
Gianluca Aiello

**Comment by damikael** [comment]
SimpleSAMLphp non prevede la gestione di più AssertionConsumerService,
tuttavia, è possibile installare più istanze di SimpleSAMLphp con spid-php 
e creare e firmare manualmente il metadata con AssertionConsumerService che puntano alle diverse istanze

**Comment by alessandrobozo** [comment]
Salve, sto sviluppando un metadata con 2 AssertionConsumerService, mi sapreste dire in fase di richiesta e di logout al validator dove devo andare ad impostare l'index del AttributeConsumingServiceIndex?
Grazie
Alessandro
