### ISSUE TITLE
Estensione Login per autenticazione SPID Persona Giuridica, Persona Fisica  uso professionale e  Persona Giuridica uso professionale 

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-php#81]
Al momento la libreria permette di effettuare l'autenticazione solo per persona fisica, escludendo le altre tipologie di identità definite nell'[Avviso SPID n°18](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf).

Nell'ottica di fornire un contributo allo sviluppo della libreria, sarebbe da preferire l'estensione del metodo login con un'ulteriore parametro "Purpose", oppure definire un diverso metodo di login per ognuno dei diversi login possibili (loginP, loginLP, loginPG, loginPF, loginPX)?

**Comment by damikael** [comment]
Sulla versione 3.4.0 è stata aggiunta la funzione [setPurpose](https://github.com/italia/spid-php#setpurpose)
