### ISSUE TITLE
Mancata gestione dell'Anomalia SPID n° 30 ed parziale gestione dell'Anomalia SPID n°25 

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-php#82]
Nei messaggi di errore non è gestito l'Errore n°30, definito nell'Avviso SPID [n°18](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf).

Segnalo inoltre che, nel caso dell'Errore n°25 (Processo di autenticazione annullato dall’utente), alcuni IdP restituiscono lo StatusMessage "Responder/RequestUnsupported: ErrorCode nr25" invece di "Responder/AuthnFailed: ErrorCode nr25".

Andrebbero gestiti entrambi i casi.

**Comment by damikael** [comment]
Risolto sulla versione [3.4.0](https://github.com/italia/spid-php/releases/tag/v.3.4.0)
