### ISSUE TITLE
Spid non funzionante con PosteId 

### ISSUE THREAD

**Issue by gianusa** [italia/spid-php#85]
Buongiorno,

dopo la pubblicazione del metadata.xml, riceviamo il messaggio di errore "Impossibile stabilire l'autenticità della richiesta di autenticazione - Contattare il gestore del servizio" quando si cerca di entrare con Spid di PosteId.

Utilizzando altri IDP come SieltID, IntesaID non rileviamo errori. 

In che modo posso capire perché PosteId non valida il SP, mentre gli altri IDP invece lo validano correttamente?

Grazie
Gianluca

**Comment by damikael** [comment]
Buongiorno @gianusa ,
potrebbe essere semplicemente un problema di allineamento del metadata.
Normalmente la propagazione del metadata avviene entro 24/48 h dal superamento del collaudo e conseguente rilascio sul registro. Se il problema persiste oltre questi tempi suggerisco in prima istanza di segnalare il problema a spid.tech@agid.gov.it chiedendo una verifica.

**Comment by gianusa** [comment]
OK, grazie!

**Comment by gianusa** [comment]
Il problema si è sistemato, ma il tempo è stato più lungo di 48H. Ci sono voluti 3 giorno lavorativi ...
