### ISSUE TITLE
element CessionarioCommittente: Schemas validity error

### ISSUE THREAD

**Issue by StefSoge** [italia/spid-php#87]
Buonasera,

per mostrare nel metadata  le informazioni obbligatorie per la fatturazione (occorrenza ContactPerson con l’attributo contactType valorizzato come billing) devo inserire nell'authsources.php i valori:
    'emailAddress'      => 'email@emal',
    'telephoneNumber'   => '+39 '
In questa condizione il check xsd di  spid-saml-check mi da questo errore:

> the metadata must validate against the XSD stderr: ./data/https___www_miosito_samlservice/sp-metadata.xml:63: element CessionarioCommittente: Schemas validity error : Element '{https://spid.gov.it/invoicing-extensions}CessionarioCommittente': This element is not expected. Expected is one of ( {https://spid.gov.it/saml-extensions}IPACode, {https://spid.gov.it/saml-extensions}VATNumber, {https://spid.gov.it/saml-extensions}FiscalCode, {https://spid.gov.it/saml-extensions}Public, {https://spid.gov.it/saml-extensions}Private ). stderr: ./data/https___www_miosito_samlservice/sp-metadata.xml fails to validate

se invece ometto i dati del billing dal metadata il check xsd restituisce  success.

il test con spid-testenv2 funziona perfettamente in entrambi i casi.

non capisco dove sia l'errore e se posso procedere con il collaudo di AGID anche in presenza di quell'errore ...

Grazie in anticipo

**Comment by AntonioGiovanniSchiavone** [comment]
Sarebbe meglio pubblicassi la parte finale del metadata (dal tag Organization in poi), eventualmente anonimizzando i dati specifici del SP. 

Potresti aver invertito l'ordine del <md:ContactPerson contactType="other"> con <md:ContactPerson contactType="billing">, avere un errore sul namespace, etc .  Difficile dirlo senza vedere il metadata.

**Comment by StefSoge** [comment]
<md:Organization>
        <md:OrganizationName xml:lang="it">
            MyOrg
        </md:OrganizationName>
        <md:OrganizationDisplayName xml:lang="it">
            MyOrgName
        </md:OrganizationDisplayName>
        <md:OrganizationURL xml:lang="it">
            http://www.myorg.it
        </md:OrganizationURL>
        
        <md:ContactPerson contactType="other">
        <md:Extensions>
          <spid:VATNumber xmlns:spid="https://spid.gov.it/saml-extensions">
                  IT12345678909
              </spid:VATNumber>
          <spid:Private xmlns:spid="https://spid.gov.it/saml-extensions"/>
        </md:Extensions>
        
    
        <md:Company>
            Mycompany
        </md:Company>
        
    
        <md:EmailAddress>
            mailto:myemai@myprov.it
        </md:EmailAddress>
        <md:TelephoneNumber>
            +39 000000
        </md:TelephoneNumber>
    </md:ContactPerson>
    
    <md:ContactPerson contactType="billing">
        <md:Extensions>
            <fpa:CessionarioCommittente xmlns:fpa="https://spid.gov.it/invoicing-extensions">
                
                <fpa:DatiAnagrafici>
                    <fpa:IdFiscaleIVA>
                        <fpa:IdPaese>
                            IT
                        </fpa:IdPaese>
                        <fpa:IdCodice>
                            IT12345678909
                        </fpa:IdCodice>
                     </fpa:IdFiscaleIVA>
                    
          
                    <fpa:Anagrafica>
                        <fpa:Denominazione>
                            myDenom
                        </fpa:Denominazione>
                    </fpa:Anagrafica>
                </fpa:DatiAnagrafici>
                
        
                <fpa:Sede>
                    <fpa:Indirizzo>
                        via 
                    </fpa:Indirizzo>
                    <fpa:NumeroCivico>
                        14
                    </fpa:NumeroCivico>
                    <fpa:CAP>
                        00000
                    </fpa:CAP>
                    <fpa:Comune>
                        mio comune
                    </fpa:Comune>
                    <fpa:Provincia>
                        XX
                    </fpa:Provincia>
                    <fpa:Nazione>
                        IT
                    </fpa:Nazione>
                 </fpa:Sede>
                
             </fpa:CessionarioCommittente>
            
    
        </md:Extensions>
        
    
        <md:Company>
            myCompany bill
        </md:Company>
        
    
        <md:EmailAddress>
            mailto:myemailbill@xxxxx.it
        </md:EmailAddress>
        <md:TelephoneNumber>
            +39 xxxx
        </md:TelephoneNumber>
        
  
    </md:ContactPerson>
    

</md:EntityDescriptor>

**Comment by AntonioGiovanniSchiavone** [comment]
Il tag Organization è aperto. Deve essere chiuso prima di  <md:ContactPerson contactType="other">

**Comment by StefSoge** [comment]
Vero!
e perchè simplesamlphp non lo chiude ?
io mi sono limitato a configurare authsources.php ....

**Comment by StefSoge** [comment]
Chiedo scusa ... ho appena verificato ... probabilmente sopra ho sbagliato il copia/incolla o la formattazione, il tag  </md:Organization> è ben presente nel metadata ....

```
<md:Organization>
    <md:OrganizationName xml:lang="it">xxxINCxxx</md:OrganizationName>
    <md:OrganizationDisplayName xml:lang="it">xxxINCxxx -</md:OrganizationDisplayName>
    <md:OrganizationURL xml:lang="it">http://www.xxxINCxxx.it</md:OrganizationURL>
  </md:Organization>
  <md:ContactPerson contactType="other">
    <md:Extensions>
      <spid:VATNumber xmlns:spid="https://spid.gov.it/saml-extensions">IT12312312312</spid:VATNumber>
      <spid:Private xmlns:spid="https://spid.gov.it/saml-extensions"/>
    </md:Extensions>
    <md:Company>Mario  Rossi</md:Company>
    <md:EmailAddress>mailto:aRossi@xxxINCxxx.it</md:EmailAddress>
    <md:TelephoneNumber>+39 0700123123</md:TelephoneNumber>
  </md:ContactPerson>
  <md:ContactPerson contactType="billing">
    <md:Extensions>
      <fpa:CessionarioCommittente xmlns:fpa="https://spid.gov.it/invoicing-extensions">
        <fpa:DatiAnagrafici>
          <fpa:IdFiscaleIVA>
            <fpa:IdPaese>IT</fpa:IdPaese>
            <fpa:IdCodice>IT12312312312</fpa:IdCodice>
          </fpa:IdFiscaleIVA>
          <fpa:Anagrafica>
            <fpa:Denominazione>Mario  Rossi</fpa:Denominazione>
          </fpa:Anagrafica>
        </fpa:DatiAnagrafici>
        <fpa:Sede>
          <fpa:Indirizzo>via xxxxVIAxxxxx</fpa:Indirizzo>
          <fpa:NumeroCivico>14</fpa:NumeroCivico>
          <fpa:CAP>06100</fpa:CAP>
          <fpa:Comune>San giustino</fpa:Comune>
          <fpa:Provincia>PP</fpa:Provincia>
          <fpa:Nazione>IT</fpa:Nazione>
        </fpa:Sede>
      </fpa:CessionarioCommittente>
    </md:Extensions>
    <md:Company>Mario  Rossi</md:Company>
    <md:EmailAddress>mailto:aRossi@xxxINCxxx.it</md:EmailAddress>
    <md:TelephoneNumber>+39 0700123123</md:TelephoneNumber>
  </md:ContactPerson>
</md:EntityDescriptor>
```

**Comment by damikael** [comment]
Il metadata è corretto, consiglio di procedere comunque con la richiesta di verifica ad AgID e aprire issue sul repository di spid-saml-check per tenere traccia dell'errore riscontrato.

**Comment by StefSoge** [comment]
thx
