### ISSUE TITLE
Problema di configurazione

### ISSUE THREAD

**Issue by francescoscialacqua** [italia/spid-php#89]
Scaricando il progetto si ottiene un errore durante la generazione del certificato. che si risolve togliendo il commento sulla riga 631 di Setup.php fwrite($openssl_config, "organizationIdentifier=2.5.4.97\n");

Segnalo che senza questa modifica non mi è possibile generare il .crt

**Comment by damikael** [comment]
Nelle ultime versioni di OpenSSL la configurazione è già definita, per questo la riga era stata commentata.
Rif. https://github.com/italia/spid-compliant-certificates/issues/3
