### ISSUE TITLE
Problema configurazione Setup.php

### ISSUE THREAD

**Issue by francescoscialacqua** [italia/spid-php#90]
Se non si toglie il commento su fwrite($openssl_config, "organizationIdentifier=2.5.4.97\n"); non si genera il certificato

**Comment by damikael** [comment]
Nelle ultime versioni di OpenSSL la configurazione è già definita, per questo la riga era stata commentata.
Rif. italia/spid-compliant-certificates#3

**Comment by francescoscialacqua** [comment]
Ok, quindi mi dici che utilizzo una versione di OpenSSL vecchia che non ha definita quella configurazione. Corretto?

**Comment by damikael** [comment]
sì @francescoscialacqua è probabile, verifica se puoi aggiornare OpenSSL
