### ISSUE TITLE
Errore di validazione

### ISSUE THREAD

**Issue by p4ever** [italia/spid-php#92]
Ciao a tutti, ho aggiornato la libreria all'ultima versione ora se provo a far un login attraverso spid via test (idptest.spid.gov.it)
ottengo un errore:

Elemento: AuthnRequest/Extensions
Dettagli dell'errore: item not allowed

**Comment by damikael** [comment]
Buongiorno @p4ever ,
verifica di non aver impostato l'istruzione **setPurpose** che permette di aggiungere nella AuthnRequest il codice Extensions che richiede l'autenticazione con identità digitale uso professionale, come previsto dalle specifiche.
Per capire meglio servirebbe analizzare la AuthnRequest che viene inviata.
In ogni caso consiglio di utilizzare spid-saml-check per effettuare test sull'implementazione.

**Comment by p4ever** [comment]
Confermo, era presente ancora la chiamata a setProfessionalUse(false), risolto rimuovendola

Grazie

**Comment by damikael** [comment]
Era effettivamente un baco. Corretto e rilasciata versione aggiornata.
Grazie @p4ever
