### ISSUE TITLE
CIE

### ISSUE THREAD

**Issue by filippoma** [italia/spid-php#95]
Salve,
volevo chiedere se questa versione è compatibile con la cie e nel caso quali sono i passi per l'integrazione.

Grazie mille

**Comment by damikael** [comment]
Buongiorno @filippoma , 
al momento spid-php prevede solo l'integrazione con SPID.
Terrò in considerazione la possibilità di aggiungere l'integrazione "out of the box" con CIE.

**Comment by eshiol** [comment]
@damikael, a parte la generazione del metadata conforme, cos'altro manca per l'autenticazione CIE?

**Comment by damikael** [comment]
Buonasera @eshiol ,
sono stati fatti nel frattempo alcuni rilasci che hanno inserito una maggiore compatibilità con CIE.
A parte il metadata, ora l'autenticazione CIE dovrebbe funzionare, dovrebbe essere sufficiente nell'installazione di simpleSAMLphp:
 
- configurare le info degli ambienti CIE in saml20-idp-remote.php
- e, preferibilmente, impostare un nuovo service specifico per CIE in authsources.php

**Comment by eshiol** [comment]
Grazie della celere risposta. Nei test effettuati riceviamo sempre la risposta
La richiesta non può essere soddisfatta poiché il messaggio ricevuto non rispetta i requisiti di sicurezza del servizio di accesso.
Confrontando l'AuthnRequest generata, con quella generata da un servizio funzionante, sembra machi la parte signature.

**Comment by damikael** [comment]
Assicurati che la richiesta venga inviata con Binding HTTP-POST, Comparison exact e livello SPID 2

**Comment by damikael** [comment]
In ogni caso a breve conto di aggiungere in fase di setup la scelta per la configurazione automatica per CIE.

**Comment by temptationisla** [comment]
Buongiorno @damikael,
come nell'issue #203 ci sono ancora degli errori di convalida. Ho risolto credo andando ad editare il file setup/simplesamlphp/simplesamlphp/lib/SimpleSAML/Metadata/SAMLBuilder.php nella funzione addContact

ho aggiunto per ogni parametro l'aggiunta dell'estensione, ad esempio:

if(isset($details['extensions']['Province'])) {
			$ext_elem_type = $ext_dom->createElementNS('https://www.cartaidentita.interno.gov.it/saml-extensions', 'cie:Province', $details['extensions']['Province']);
			$eexts[] = new \SAML2\XML\Chunk($ext_elem_type);			
		}

Credo che ti potrebbe essere utile per un aggiornamento del componente

Saluti

**Comment by damikael** [comment]
@temptationisla , il problema dovrebbe essere stato risolto con le ultime versioni.

Per eventuali altre segnalazioni, chiedo gentilmente di aprire nuove issue.
Grazie
