### ISSUE TITLE
Personalizzazione pagine errori

### ISSUE THREAD

**Issue by francescoscialacqua** [italia/spid-php#96]
Sto finendo l'implementazione della mia pagina di accesso SPID ma trovo difficoltà nell'utilizzo della classe Error.php che gestirebbe gli errori comsì come definiti da documentazione AGID.

Nello specifico ho realizzato un tema SimpleSalmphp personalizzato ma non riesco a capire come usare la classe e quindi personalizzare i messaggi di errore. Avete qualche indicazione da darmi in merito?

**Comment by damikael** [comment]
In caso di errore, viene richiamata la pagina error.php:
spid-php/vendor/simplesamlphp/simplesamlphp/templates/error.php
oppure la pagina error.php definita nel proprio tema.

I codici e i messaggi di errore sono disponibili nell'array data e accessibili come segue:

$this->data['error']['statusCode']);
$this->data['error']['statusMessage']);
$this->data['errorMessage']

In particolare errorMessage contiene i messaggi delle anomalie derivanti dall'utente definite per SPID.

è sufficiente quindi personalizzare il template html della pagina error.php

**Comment by francescoscialacqua** [comment]
Grazie mille per la celere risposta. 
Ho seguito queste indicazioni solo che gli errori mi arrivano tutti sotto forma di Eccezione non gestita.

Ad esempio non test 2 del validatore ottengo The assertion was not signed. Errore non identificato

**Comment by damikael** [comment]
Sì, tutti gli errori possono essere nascosti da un semplice messaggio di errore generico, 
ad eccezione degli errori derivanti dalle anomalie utente (test response di spid-saml-check 104-108, 111) 
per i quali occorre presentare all'utente un messaggio conforme a quanto previsto nella [tabella anomalie spid ](https://www.agid.gov.it/sites/default/files/repository_files/tabella-messaggi-spid-v1.3_0.pdf) per le anomalie derivanti dall'utente e recuperabile nella variabile errorMessage.

**Comment by francescoscialacqua** [comment]
Ok grazie. Tutto chiaro. Dovrei essere pronto per la validazione. Incrociamo le dita.
